### ISSUE TITLE
better `auto` for angle in `geom_cladelabel()`

### ISSUE THREAD

**Issue by Rekyt** [YuLab-SMU/ggtree#130]
Hi,
First an immense thank you for building `ggtree`  I've been using since the beginning an as a `ggplot2` fan I was always disappointed to miss `ggplot2` functionality when plotting phylogenetic trees.
Also thanks for adding the `geom_cladelabel()` function which is exactly what I wanted for a really long time.
I am using the last development version of `ggtree` and use the `auto` angle value for `geom_cladelabel()`.
And when using a full fan layout the text can be inverted which makes it difficult to read:
```r
library(ggtree)

set.seed(2017-05-19)

my_tree = rtree(50)

clade_df = data.frame(node = c(52, 71, 80, 94),
                          clade = paste0("clade_", 1:4),
                          color = rep(c("#000000", "#AAAAAA"), size = 4))

clade_labels = apply(clade_df, 1, function(x) {
    list(geom_cladelabel(x[["node"]],
                         x[["clade"]],
                         color = x[["color"]],
                         angle = "auto"))
})
                          
ggtree(my_tree, layout = "fan") +
    clade_labels
```
![image](https://cloud.githubusercontent.com/assets/5593751/26256295/c64d6b9e-3cbc-11e7-8791-51cd973892f1.png)

The clades and the left have their labels upside-down.

I was thinking maybe of a better (more readable) default for `auto` like choosing computing the angle modulo 90, so that it's always readable. I can submit a pull request if you want.

**Comment by GuangchuangYu** [comment]
thanks. PR is welcome.

**Comment by GuangchuangYu** [comment]
this should be addressed by the `geom_cladelab` layer, which is a better implementation by @xiangpin

**Comment by dindiarto** [comment]
Hi @GuangchuangYu , 

Thank you for your efforts in constructing `ggtree`. I tried to re-run @Rekyt's  code and  applied @xiangpin's `geom_cladelab` instead of `geom_cladelabel` , the clade labels are still inverted. If the `angle = "auto"` can be further improved as @Rekyt suggested that would be very helpful.

```
library(ggtree)
packageVersion("ggtree")
#> [1] '2.5.2'
```
```
set.seed(2017-05-19)
my_tree = rtree(50)
clade_df = data.frame(node = c(52, 71, 80, 94),
                      clade = paste0("clade_", 1:4),
                      color = rep(c("#000000", "#AAAAAA"), size = 4))

clade_labels = apply(clade_df, 1, function(x) {
  list(geom_cladelab(x[["node"]],
                       x[["clade"]],
                       offset = 2,
                       offset.text = 1,
                       fontsize = 5,
                       color = x[["color"]],
                       angle = "auto"))
})

ggtree(my_tree, layout = "fan") +
  clade_labels
```

![image](https://user-images.githubusercontent.com/14798903/117087186-12f7eb00-ad92-11eb-9337-2b985a50815f.png)
