### ISSUE TITLE
geom_motif

### ISSUE THREAD

**Issue by GuangchuangYu** [YuLab-SMU/ggtree#148]
> the `geom_motif`, which is a wrapper layer from `gggenes::geom_gene_arrow`, works with `ggtree::facet_plot`

```r
library(gggenes)
library(ggtree)
set.seed(123)
tr = rtree(13)
tr$tip.label = sub('t', 'Genome', tr$tip.label)
g = ggtree(tr)
facet_plot(g, panel='alignment', 
        mapping = aes(xmin = start, xmax = end, x=start, y=y, fill = gene), 
        data=gggenes_example_genes, on='genE', geom=geom_motif)
```

![screenshot 2017-08-22 15 57 41](https://user-images.githubusercontent.com/626539/29554814-1f470f30-8753-11e7-85f5-75c4534eb216.png)

**Comment by GuangchuangYu** [comment]
a more beautiful version of <https://github.com/tengfei/ggbio/issues/83>.

**Comment by wilkox** [comment]
@GuangchuangYu I've put gggenes up on CRAN so you can import it if you want.

**Comment by chxp** [comment]
Cannot reproduce the results from the issue
https://github.com/GuangchuangYu/ggtree/issues/148

Is anything changed from that time?

My code is following:
```R
library(gggenes)
library(ggtree)
data(example_genes)

set.seed(123)
tr <- rtree(13)
tr$tip.label <- sub('t', 'Genome', tr$tip.label)
g <- ggtree(tr)

facet_plot(g, panel='alignment', 
        mapping=aes(xmin=start, xmax=end, x=start, y=y, fill=gene), 
        data=example_genes, on='genE', geom=geom_motif)
```

I change the `data=gggenes_example_genes` in previous code to `data=example_genes`, it seems the two are the same.

It is hard to see the example of geom_motif, so i ask it here, thanks.

**Comment by MichWeb75** [comment]
I tried to use the code and end up with following error code
`Error in `[.data.frame`(data, , id) : undefined columns selected`
```
library(gggenes)
library(ggtree)
set.seed(123)
tr = rtree(13)
tr$tip.label = sub('t', 'Genome', tr$tip.label)
g = ggtree(tr)
facet_plot(g, panel='alignment', 
        mapping = aes(xmin = start, xmax = end, x=start, y=y, fill = gene), 
        data=gggenes_example_genes, on='genE', geom=geom_motif)
```

**Comment by GuangchuangYu** [comment]
example presented here, <https://yulab-smu.github.io/treedata-book/chapter11.html#genome-locus>, using ggtree v>=1.17.5.
