### ISSUE TITLE
Legends for geom_hilights

### ISSUE THREAD

**Issue by reptalex** [YuLab-SMU/ggtree#149]
Is there a way to make legends for geom_hilight? I've tried using scale_fill_manual and guide_legend, but can't seem to produce a legend mapping the colors in the geom_hilight to string labels.

Also, if you know how to do this with many overlaid, transparent geom_higlights, that would be super helpful (e.g. a green, transparent geom_hilight on top of a red geom_hilight from a basal node)!

P.S. I love the package - it has been invaluable for illustrating my research. Thank you!

### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://guangchuangyu.github.io/ggtree/documentation/)
	* [x] google your quesion/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ ] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

**Comment by GuangchuangYu** [comment]
Maybe I need to develop a `geom_hilight2` function that accept a vector of nodes and automatically generate the legend.

For current implementation, `geom_hilight` will not generate the legend as it using color specifying by user instead of mapping it to variable using `aes`.

However, it is always possible to post-process the `ggtree` object to modify details. To solve this requested issue, I implemented a `set_hilight_legend` function to do the trick.

```r
library(ape)
library(ggtree)

set.seed(1)

tree <- rtree(10)
nds <- c(12,14,16)
cls <- c('blue','red','green')
alphas <- c(0.8,0.7,0.3)
names <- c('Clade 1','Clade 2','Clade 3')

gg <- ggtree(tree)
for (i in 1:3){
  gg <- gg+geom_hilight(nds[i],cls[i],alpha = alphas[i])
}

p1 = set_hilight_legend(gg, cls, names) + theme(legend.position="right")



gg <- ggtree(tree)
for (i in 1:3){
  gg <- gg+geom_hilight(nds[i],cls[i], alpha=1)
}

gg$layers = c(gg$layers[-(1:2)], gg$layers[1:2])
p2 = set_hilight_legend(gg, cls, names) + theme(legend.position="right")

cowplot::plot_grid(p1, p2, ncol=2)
```

![screenshot 2017-08-30 14 22 48](https://user-images.githubusercontent.com/626539/29858224-10870d82-8d8f-11e7-80e2-2b39b764fea8.png)

**Comment by GuangchuangYu** [comment]
now the function supports `alpha` parameter:

```
p1 = set_hilight_legend(gg, cls, names, alpha=alphas) + theme(legend.position="right")
```
![screenshot 2017-11-15 14 42 18](https://user-images.githubusercontent.com/626539/32822415-5f01f6dc-ca13-11e7-9382-4938bbc6a2d3.png)

**Comment by claireonthecouch** [comment]
Hi, it appears that set_hilight_legend automatically orders the factors alphabetically. In my case, this means that the factors won't match up with the correct colors. How do I get around this?

**Comment by GuangchuangYu** [comment]
problem solved by <https://github.com/YuLab-SMU/ggtree/pull/326>.
