### ISSUE TITLE
Control border size in gheatmap

### ISSUE THREAD

**Issue by mw55309** [YuLab-SMU/ggtree#158]
Hi

I am running ggtree_1.6.11  on Windows.

Is there a way to adjust the size of the borders in gheatmap such that the text fits?  If I set angle to 90, then the text is readable but overlaps the heatmap

Thanks
Mick

**Comment by GuangchuangYu** [comment]
you just ignore the [msg](https://github.com/GuangchuangYu/ggtree/issues/new).

**Comment by Espinosa-Gongora** [comment]
Same issue. Long vertical colnames will not be printed regardless of margins or plotting area adjustments. Any developments since 2017? 
Not sure what message Dr Yu refers to :-)

**Comment by ammaraziz** [comment]
If you are still having issues see my comment here:
https://github.com/YuLab-SMU/ggtree/issues/367

**Comment by GuangchuangYu** [comment]
something like `g + ggtree::vexpand(.1, -1)` should works for you, see <https://yulab-smu.top/treedata-book/chapter12.html?q=vexpand#ggexpand>
