### ISSUE TITLE
The color of geom_nodepoint can't represented by variation

### ISSUE THREAD

**Issue by Adam-JJJJJ** [YuLab-SMU/ggtree#245]
Hi, Repect Doc Yu:
  When i used your  masterpiece ggtree, the color of function geom_nodepoint was  troubled  me. I want make the gradient color of nodepoint change with bootstrap value. However, when i write
 `a<-read.tree("GST.nwk")`
 `p <- ggtree(a) + 
  geom_tiplab(size=3)+
  geom_nodepoint(aes(color=a$node.label))`,
R reported an error that: Error: Aesthetics must be either length 1 or the same as the data (30): colour. I had verified my parameter of `a$node.label`and its length is 14 which is the same numbers as nodepoint.  
The sample of your manual only show one color`p <- ggtree(tree) + geom_nodepoint(color="#b5e521", alpha=1/4, size=10)
p + geom_tippoint(color="#FDAC4F", shape=8, size=3)`. May i ask  that how can color represented by var?
Thanks for ur time.

**Comment by GuangchuangYu** [comment]
see <https://yulab-smu.github.io/treedata-book/faq.html#faq-dollar-aes> and <https://yulab-smu.github.io/treedata-book/chapter4.html#color-tree>.

**Comment by brj1** [comment]
When a `phylo` object (tree) is passed into the `ggtree` function (or `ggplot` function for that matter) it is fortified into a `tibble`. The node.label and tip.label in the `phylo` object are combined into the `label` column. So to colour your nodes by the bootstrap value you will need to use `color=label` as your aesthetic or better `color=as.numeric(label)` to ensure that the labels are treated as numbers instead of strings. The latter may give a warning, but it should be fine. So the following should work:

```R
p <- ggtree(a) + geom_tiplab(size=3)+ geom_nodepoint(aes(color=as.numeric(label)))
```

**Comment by Adam-JJJJJ** [comment]
> When a `phylo` object (tree) is passed into the `ggtree` function (or `ggplot` function for that matter) it is fortified into a `tibble`. The node.label and tip.label in the `phylo` object are combined into the `label` column. So to colour your nodes by the bootstrap value you will need to use `color=label` as your aesthetic or better `color=as.numeric(label)` to ensure that the labels are treated as numbers instead of strings. The latter may give a warning, but it should be fine. So the following should work:
> 
> ```r
> p <- ggtree(a) + geom_tiplab(size=3)+ geom_nodepoint(aes(color=as.numeric(label)))
> ```

Thank u very much.

**Comment by Adam-JJJJJ** [comment]
> see https://yulab-smu.github.io/treedata-book/faq.html#faq-dollar-aes and https://yulab-smu.github.io/treedata-book/chapter4.html#color-tree.

Appreciate your help.
