### ISSUE TITLE
geom_inset error

### ISSUE THREAD

**Issue by michunrong124** [YuLab-SMU/ggtree#247]
Dear All,

When I try to run the example of ggtree in 
https://yulab-smu.github.io/treedata-book/chapter8.html
**8.3.1 Annotate with bar charts**
...
p + geom_inset(bars, width = .08, height = .05, x = "branch") 

I found an error 
Error in geom_inset(bars, width = 0.1, height = 0.1) : 
  could not find function "geom_inset"

I also have try to download the source code and run in R 
https://github.com/YuLab-SMU/ggtree/blob/master/R/inset.R
but still an Error occur:
Error: Don't know how to add geom_inset(bars, width = 0.1, height = 0.1) to a plot

Anyone know how to deal with it?

Beset wishes,
Mi

**Comment by GuangchuangYu** [comment]
the `geom_inset` was introduced in v >= 1.17.2, see <https://github.com/YuLab-SMU/ggtree/blob/master/NEWS.md#ggtree-1172>.

pls install the github version of `ggtree`.
