### ISSUE TITLE
facet_plot, variable x axis scales

### ISSUE THREAD

**Issue by brj1** [YuLab-SMU/ggtree#257]
Hi Yu,

Is it possible use different `x_scale`s in `facet_plot`? I want to put axis titles in my plot, but I can't figure out how to do it. The best I can do is make an axis title with a lot of spaces in it, but then the centering is hard to do. I also tried using the facet labels, but I couldn't figure out how to get them moved from the top to the bottom. I think this might be limitation of facets in general.

I want to do something like the following but without the spaces: 

```R
library(ggtree)
library(ggplot2)
set.seed(2019-05-02)
x <- rtree(30)
p <- ggtree(x) + geom_tiplab()
d <- data.frame(label = x$tip.label, 
                value = rnorm(30))
p2 <- facet_plot(p, panel = "Dot", data = d, 
            geom = geom_point, mapping = aes(x = value))
p2 + xlim_tree(6) + xlim_expand(c(-10, 10), 'Dot') + scale_x_continuous(name=c("Distance                                                                 Dot Units")) + theme_bw()
````

Thanks.

**Comment by GuangchuangYu** [comment]
```
d = data.frame(.panel = c('Tree', 'Dot'), 
                lab = c("Distance", "Dot Units"), 
                x=c(3,0), y=-2)

p2 + xlim_tree(6) + xlim_expand(c(-10, 10), 'Dot') +
    scale_y_continuous(limits=c(0, 31), expand=c(0,0), oob=function(x, ...) x) +
    geom_text(aes(label=lab), data=d) + 
    coord_cartesian(clip='off')  + 
    theme_bw() +
    theme(plot.margin=margin(6, 6, 40, 6))
```

**Comment by GuangchuangYu** [comment]
in [FAQ](https://yulab-smu.github.io/treedata-book/faq.html#different-x-labels-for-different-facet-panels) now.
