### ISSUE TITLE
line size of the tree itself not the treescale...

### ISSUE THREAD

**Issue by cjieming2** [YuLab-SMU/ggtree#258]
Hi is there a way to chnage the line width of the branches of the tree itself? I couldn't find any parameters controlling that. 
Thanks.

**Comment by GuangchuangYu** [comment]
see figure 4.1B on <file:///home/ygc/github/treedata-book/docs/chapter4.html#visualizing-phylogenetic-tree-with-ggtree>.

You can use `size` parameter.
