### ISSUE TITLE
similar to heatmap but prefer circle sizes

### ISSUE THREAD

**Issue by maoweiliang** [YuLab-SMU/ggtree#259]
### Prerequisites

+ [ ] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [ ] google your question/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ ] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)
I wanna this one
![1](https://user-images.githubusercontent.com/25013103/67665061-e21c4600-f9a3-11e9-8afa-e48e5bdc6adc.png)
But I made one 
![Rplot](https://user-images.githubusercontent.com/25013103/67665123-0aa44000-f9a4-11e9-8a94-7711a2b9930f.png)
NG, LG, ML, and HG are treatments, and the values are abundances of species. 

Thank you very much in advance.

**Comment by GuangchuangYu** [comment]
for user question, please post to <https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/bioc-ggtree>.
