### ISSUE TITLE
parameter `width` not working in geom_facet

### ISSUE THREAD

**Issue by lch14forever** [YuLab-SMU/ggtree#261]
I am assuming the `width` parameter in `geom_facet` is to control the relative width of the newly added panel according to this example:
https://yulab-smu.github.io/treedata-book/chapter7.html#facet_plot

However, it doesn't seem to be working properly yet (adding the parameter had no effect)...

```r
library(ggtree)
set.seed(1)
tr <- rtree(10)
dat <- data.frame(node=tr$tip.label, dat=rnorm(1))
ggtree(tr) + 
  geom_facet(panel='This is a test', data=dat, geom=geom_point, 
             mapping=aes(x = dat), width = .1)
```

```r
Warning: Ignoring unknown parameters: width
```

**Comment by brj1** [comment]
The `width` is actually not one of `geom_facet` parameters, but in the example one of the `...` parameters. It is passed to the `geom`, which in the example's case is `ggstance::geom_barh`. In `ggstance::geom_barh` the `width` parameter specifies the bar width.

**Comment by lch14forever** [comment]
That explains. Thanks!

**Comment by GuangchuangYu** [comment]
currently, the only way to adjust facet width is described in <https://yulab-smu.github.io/treedata-book/chapter10.html#facet_widths>.
