### ISSUE TITLE
"continuous = TRUE" not working

### ISSUE THREAD

**Issue by Si-Chong** [YuLab-SMU/ggtree#263]
Hello Guangchuang.

I am trying to work my tree by learning from your code in the tutorial document:
Figure 4.11: Continuous state transition in edges

ggtree(tree, aes(color=trait), layout = 'circular', 
        ladderize = FALSE, continuous = TRUE, size=2) +
    scale_color_gradientn(colours=c("red", 'orange', 'green', 'cyan', 'blue')) +
    geom_tiplab(hjust = -.1) + xlim(0, 1.2) + theme(legend.position = c(.05, .85)) 

However, R gives two lines of warning message (the two lines are the same):
Warning: Ignoring unknown parameters: continuous
Warning: Ignoring unknown parameters: continuous

The graph can be shown, but the state transition in edges are not continuous, but discrete (i.e. change suddenly from green to blue, as below).
I appreciate if you could please point out the secret to make the edge colour in gradient (just as your example). Thank you!
![image](https://user-images.githubusercontent.com/49397144/69566443-040ee580-0faf-11ea-89f3-fec8645979e5.png)

### Prerequisites

+ [Yes] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [Yes] make sure your are using the latest release version
	* [Yes] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [Yes] google your question/issue

### Describe you issue

* [Yes] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [Yes] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [Yes] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

**Comment by GuangchuangYu** [comment]
if you follow the guide carefully, you can figure it out.

### Prerequisites

+ [ ] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [ ] google your question/issue

**Comment by Si-Chong** [comment]
Thank you. I have read the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/) and made sure clusterProfiler is the latest (3.12.0). Also, R (3.6.1), ggplot2 and ggtree are also the latest. I am using the github version of treeio, as you suggested in another post.
However, the problem of "continuous = TRUE" persists. My purpose is to reproduce Figure 4.11 in the [document](https://yulab-smu.github.io/treedata-book/chapter4.html)
The code gives:
![image](https://user-images.githubusercontent.com/49397144/69623362-a6c07600-103a-11ea-9911-5697389fa77d.png)

I also read vignette and googled the continuous parameter, but all relevant information is directed to the tutorial document.
Thanks for helping me out.

**Comment by brj1** [comment]
Are you using the latest version of ggtree? I suggest installing the github version of ggtree.

```r
devtools::install_github("YuLab-SMU/ggtree")
```

**Comment by Si-Chong** [comment]
> Are you using the latest version of ggtree? I suggest installing the github version of ggtree.
> 
> ```r
> devtools::install_github("YuLab-SMU/ggtree")
> ```

Thank you! All solved. I am grateful.
I was using the BiocManager version of ggtree.
