### ISSUE TITLE
ggdenditree with group colored

### ISSUE THREAD

**Issue by Yujiaxin419** [YuLab-SMU/ggtree#265]
Dear  Professor Yu:
    Is there has any solution to plot a densitree  which different group with different color?
    for instant, fig.1 in the end.
    I will be very grateful, if you reply me in your busy day. thanks.
                                                                                                                     yujiaxin

![image](https://user-images.githubusercontent.com/52374093/70203243-36f76d00-1757-11ea-9990-5c3b67143bab.png)

**Comment by GuangchuangYu** [comment]
if you try the example presented in ?ggdensitree, you will find an answer.

here is a modify version to directly answer your question:

```
set.seed(1)
trees <- rmtree(5, 10)
time.trees <- lapply(1:length(trees), function(i) {
             tree <- trees[[i]]
             tree$tip.label <- paste0("t", 1:10)
             dates <- estimate.dates(tree, 1:10, mu=1, nsteps=1)
             tree$edge.length <- dates[tree$edge[, 2]] - dates[tree$edge[, 1]]
             fortify(tree) %>% mutate(tree=factor(i, levels=as.character(1:10)))
}) 

grp <- list(A = c('t1', 't2', 't3'),
            B = c('t4', 't5', 't6'),
            C = c('t7', 't8', 't9', 't10'))
time.trees <- lapply(time.trees, function(x) groupOTU(x, grp))            
ggdensitree(time.trees, aes(colour=group), tip.order=paste0("t", 1:10)) + geom_tiplab(colour='black')
```

**Comment by brj1** [comment]
I added example to `ggdensitree`'s man page that is similar to @GuangchuangYu 's example. PR #267
