### ISSUE TITLE
Images inherit colour aesthetic

### ISSUE THREAD

**Issue by mdhall272** [YuLab-SMU/ggtree#270]
If you annotate nodes with an image, and also colour branches according to another variable, those colours fill in the image.

MWE:
```
library(ggtree)
library(ape)

tr <- rtree(14)

imgfile <- tempfile(, fileext=".jpg", tmpdir = getwd())
download.file("https://upload.wikimedia.org/wikipedia/commons/e/eb/Ash_Tree_-_geograph.org.uk_-_590710.jpg", destfile=imgfile, mode='wb')

# This works as one would hope

ggtree(tr) + geom_nodelab(aes(image = rep(imgfile, 27)), geom="image")

# But here the images become blocks of colour

ggtree(tr, aes(col = sample(rep(c("A", "B", "C"), each = 9)))) + geom_nodelab(aes(image = rep(imgfile, 27)), geom="image")

```
I've tried various things - setting `col=NA` or `col="black"` or even `alpha=0` within `geom_nodelab` to no avail. It seems to me that the trouble is that, unless I'm mistaken, there is no way in ggtree to specify that an aesthetic applies only to branches?

**Comment by GuangchuangYu** [comment]
see examples in <https://yulab-smu.github.io/treedata-book/chapter8.html>.

**Comment by mdhall272** [comment]
Nothing in the vignette, which I am very familiar with and studied before submitting the issue, tells me how to colour branches without colouring in the image.

**Comment by GuangchuangYu** [comment]
using phylopic is almost identical to use your own images. It just download the images online instead of reading local files.
```
ggtree(tree, aes(color = VAR)) + geom_image(..., inherit.aes=FALSE)
```

with `inherit.aes=FALSE`, `geom_image` will not inherit aes from `ggtree`.
