### ISSUE TITLE
ggtree for dendrograms:MRCA function meets error

### ISSUE THREAD

**Issue by LuffyLuffy** [YuLab-SMU/ggtree#271]
### Prerequisites
Hi there,
when I try to run examples https://yulab-smu.github.io/treedata-book/chapter9.html with code
library(ggtree)
library(tidytree)
hc <- hclust(dist(mtcars))
hc
clus <- cutree(hc, 4)
g <- split(names(clus), clus)

p <- ggtree(hc, linetype='dashed')
clades <- sapply(g, function(n) MRCA(p, n))

library(ggtree)
library(tidytree)
hc <- hclust(dist(mtcars))
hc
clus <- cutree(hc, 4)
g <- split(names(clus), clus)

p <- ggtree(hc, linetype='dashed')
clades <- sapply(g, function(n) MRCA(p$data, n))

Error in MRCA(.data$data, .node1, .node2, ...) : 
  argument ".node2" is missing, with no default
Called from: MRCA.tbl_tree(.data$data, .node1, .node2, ...)

I use version 1.7.4.
I'll check if the new version is OK.

+ [ ] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [ ] google your question/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ ] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

**Comment by GuangchuangYu** [comment]
pls update to current release.

**Comment by LuffyLuffy** [comment]
I update it to the current release.
it meets other errors.
p <- ggtree(hc, linetype='dashed')
Error: `data` must be a data frame, or other object coercible by `fortify()`, not an integer vector

**Comment by brj1** [comment]
It works if you run the latest dev version:

```R
library(devtools)
install_github("YuLab_SMU/github")
```

I got the same error message as @LuffyLuffy when I ran the BioConductor version.

**Comment by LuffyLuffy** [comment]
Thanks a lot, 
I try to tidytree first then install from github. It works! 

install.packages('tidytree')
library(devtools)
install_github("YuLab-SMU/ggtree")

**Comment by LovaRandriantseheno** [comment]
Hello,
I have tried all of what you suggested, still I got this error:
Error in MRCA.phylo(tree, tip = c("307-1999B", "363-1997B")) : 
  argument ".node1" is missing, with no default
Has anyone found another solution?

**Comment by xiangpin** [comment]
How about using `MRCA(tree, .node1 = c("307-1999B", "363-1997B"))` ?

**Comment by LovaRandriantseheno** [comment]
> 

Oh, yes, it's working! Thank you for your kind help!
