### ISSUE TITLE
geom_tiplab does not work with geom_tree

### ISSUE THREAD

**Issue by brj1** [YuLab-SMU/ggtree#272]
Hi Guangchuang,

I found a weird bug today when I was trying to make a tree with scaled branch lengths based on node dates. I was plotting my trees using `fortify(tree) %>% ggplot() + geom_tree()` instead of `ggtree(tree)` and I found I could not get `geom_tiplab` to work. See the following example:

```R
library(ggtree)
library(ape)

set.seed(0)
tree <- rtree(5)

# The following works
fortify(tree) %>% ggtree() + geom_tiplab()

# But this fails
fortify(tree) %>% ggplot() + geom_tree() + geom_tiplab()

# And so does this
ggplot(tree) + geom_tree() + geom_tiplab()
```
Below is the error message I get for both failing lines above

> Error in layout == "circular" : 
  comparison (1) is possible only for atomic and list types

I am using the dev version of ggtree.

**Comment by GuangchuangYu** [comment]
fixed in v >= 2.1.2
