### ISSUE TITLE
Alternating solid and washed out colors in heatmap...sure there is easy fix to this.

### ISSUE THREAD

**Issue by slvrshot** [YuLab-SMU/ggtree#276]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [ ] google your question/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ ] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)
![image](https://user-images.githubusercontent.com/16061438/74049714-b812f080-49a2-11ea-9906-36e0d9474386.png)

I am using gheatmap to add metadata to my time dated phylogeny and it keeps doing this strange alternating color pattern. I have attempted to play around with scale fill manual but it hasn't help. I just want my colors to be solid, not a mix match of solid and washed out colors. Please help.

```
p2 <- gheatmap(pp, test, offset=.01, width=1, colnames=TRUE, font.size =3, colnames_position = "top",colnames_angle = 45, colnames_offset_y=10, hjust=0) +
  scale_fill_manual(values=cols, breaks = c("North America","Asia,"South America","Unknown",
          "Europe","Oceania","Susceptible","Elevated", "Other",
        "TRUE","WT","Mutation") + scale_x_continuous(breaks=c(1880,1890,1900,1910,1920,1930,1940,1960,1980,2000,2020))
p2
```

**Comment by brj1** [comment]
It will be easier to help you if you:

 - [ ]  Make a reproducible example (e.g. [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))

Specially, what are`pp`, `test`, `cols`?

**Comment by brj1** [comment]
I suspect I might have figured out your issue. By default `gheatmap` puts a white box around each cell in the heatmap, but if you have a lot of tips in your tree then these boxes start to lighten the heatmap. This can be fixed by setting `color = FALSE` in `gheatmap` to remove the boxes.

```R
p2 <- gheatmap(pp, test, color = FALSE, offset=.01, width=1, colnames=TRUE, font.size =3, colnames_position = "top",colnames_angle = 45, colnames_offset_y=10, hjust=0) +
  scale_fill_manual(values=cols, breaks = c("North America","Asia,"South America","Unknown",
          "Europe","Oceania","Susceptible","Elevated", "Other",
        "TRUE","WT","Mutation") + scale_x_continuous(breaks=c(1880,1890,1900,1910,1920,1930,1940,1960,1980,2000,2020))
p2
```

**Comment by slvrshot** [comment]
> I suspect I might have figured out your issue. By default gheatmap puts a white box around each cell in the heatmap, but if you have a lot of tips in your tree then these boxes start to lighten the heatmap. This can be fixed by setting color = FALSE in gheatmap to remove the boxes.
> p2 <- gheatmap(pp, test, color = FALSE, offset=.01, width=1, colnames=TRUE, font.size =3, colnames_position = "top",colnames_angle = 45, colnames_offset_y=10, hjust=0) +
>   scale_fill_manual(values=cols, breaks = c("North America","Asia,"South America","Unknown",
>           "Europe","Oceania","Susceptible","Elevated", "Other",
>         "TRUE","WT","Mutation") + scale_x_continuous(breaks=c(1880,1890,1900,1910,1920,1930,1940,1960,1980,2000,2020))
> p2

I am so sorry. I've been trying to put together a reproducible example which I meant to provide last night. I was following a tutorial that utilizes treestructure. The best example would probably be on the tutorial page. I tried color= FALSE and it fixed the problem. Thank you so much!
