### ISSUE TITLE
adding a tree scale for the second tree when plotting two trees face to face

### ISSUE THREAD

**Issue by saadarif** [YuLab-SMU/ggtree#278]
Hi there,

I'm trying to use ggtree to plot two trees face to face. I add the other tree using geom_tree() as described in the book (https://yulab-smu.github.io/treedata-book/chapter2.html section 2.5 figure 2.6) for this feature. I was just wondering if there was a straightforward way to plot the tree scale bar for the 2nd/right tree as geom_treescale does not have a data argument?

Any help would be appreciated.

best,
Saad

**Comment by brj1** [comment]
I believe that the scale should be the same for both trees. If want to have two tree scales you can add `geom_treescale()` twice and shift one of the scales' `x` value: `geom_treescale(x=1)` for example.
