### ISSUE TITLE
Error: C stack usage 7970592 is too close to the limit

### ISSUE THREAD

**Issue by bjmt** [YuLab-SMU/ggtree#282]
Hi,

After updating my R library, some of my code using in my R package `universalmotif` which makes use of `ggtree` stopped working. (Unfortunately I didn't pay attention to which packages were being udpated..) Now, when I try and make a daylight-type tree with the following code:

```r
library(ggtree)

tree <- structure(list(edge = structure(c(11L, 12L, 12L, 15L, 15L, 18L, 
18L, 11L, 13L, 13L, 14L, 16L, 16L, 19L, 19L, 14L, 17L, 17L, 12L, 
5L, 15L, 3L, 18L, 8L, 10L, 13L, 6L, 14L, 16L, 7L, 19L, 1L, 9L, 
17L, 2L, 4L), .Dim = c(18L, 2L)), edge.length = c(0.0927242860577699, 
0.324721682265531, 0.0649634641312452, 0.259758218134286, 0.118552314265711, 
0.141205903868575, 0.141205903868575, 0.077018551122174, 0.340427417201127, 
0.0439869396195794, 0.0735265359696097, 0.222913941611938, 0.0452405003771553, 
0.177673441234783, 0.177673441234783, 0.0583168215776368, 0.238123656003911, 
0.238123656003911), tip.label = c("Mafg", "CLOCK", "SREBF1", 
"dys", "PFL1085w", "TFAP4", "CEBPA", "Hlf", "Atf3", "CEBPG"), 
    Nnode = 9L), class = "phylo", order = "cladewise", group = structure(c(3L, 
2L, 2L, 2L, 1L, 2L, 3L, 3L, 3L, 3L, 2L, 1L, 2L, 2L, 2L, 3L, 2L, 
3L, 3L), .Label = c("AP2", "bHLH", "bZIP"), class = "factor"))

ggtree(tree, layout = "daylight")
```

 I get a C stack usage/infinite recursion error. Looking at the traceback reveals that the lines:

```r
mutate.tbl_tree(., angle = ifelse(.data$node %in% nodes, getNodeAngle.vector(x_parent, y_parent, .data$x, .data$y) %>% {
  180 * ifelse(. < 0, 2 + ., .)
}, .data$angle))
NextMethod()
```

are being repeated infinitely. Looking at the build systems for my package on BioConductor, macOS/Windows/Linux are all throwing the same errors for both R 3.6.3 and devel.

Any kind of help would be appreciated -- even if just advice as to what I could do to avoid this error. For now, all I can think of is to avoid using the daylight layout.

**Comment by GuangchuangYu** [comment]
fixed.
