### ISSUE TITLE
layout_dendogram issue

### ISSUE THREAD

**Issue by anuravi1234** [YuLab-SMU/ggtree#291]
Hello,

I have been following your tutorial and I was able to make really nice trees with metadata. However, I am having an issue with layout_dendrogram(). I have reinstall my ggtree and this function is not associated with ggtree. Is this a different package since it is not mentioned in your tutorial?

Could you please assist me with this?

Thanks!

Anu

**Comment by brj1** [comment]
I cannot reproduce. Your issue may be that you are not reinstalling ggtree correctly. Try detaching ggtree first and then reinstalling.

```R
detach("package:ggtree", unload=TRUE)

BiocManager:install("ggtree")
```
