### ISSUE TITLE
Tip order again - extract tips in order of tree display

### ISSUE THREAD

**Issue by ewallace** [YuLab-SMU/ggtree#298]
Hello,
Thanks for this great package. I have another question about the tip order. Basically I would like to be able to take a tree as displayed, and then use the order of tips in that as input for external libraries. For example, to order a multiple sequence alignment the same way in an output file, or to create a more customized heatmap or other plot.

There are previous similar issues such as #29, but no fixes for this exact need. A similar issue #157 was the source of this reprex that I adapted.

```
library(ape)
set.seed(42)
# construct original and reordered random trees
tree_original  <- rtree(5)
tree_reordered <- ape::rotateConstr(x, c('t1', 't4', 't5', 't3', 't2'))


library(ggtree)
# ggtree plots these as different
ggt_original  <- ggtree::ggtree(tree_original, ladderize=FALSE) + geom_tiplab()
ggt_original
ggt_reordered <- ggtree::ggtree(tree_reordered,ladderize=FALSE) + geom_tiplab()
ggt_reordered

# the order of tips in fortify(tree_original) is the same as displayed
fortify(tree_original) %>% filter(isTip)

# the order of tips in fortify(tree_reordered) is different from displayed
fortify(tree_reordered) %>% filter(isTip)
```

What I would like is a function that extracts the tip labels in the order that they are plotted.

*Either*
`extract_tip_order(ggt_original)` would give values `"t1", "t2", "t4", "t3", "t5"`;
`extract_tip_order(ggt_reordered)` would give values `"t1", "t4", "t5", "t3", "t2"`;

*or*
`extract_tree_data(ggt_reordered,displayorder=TRUE)`, giving the tree data as a tibble, with rows in order that the nodes are displayed.

UPDATE for default display settings, `layout = "rectangular"`, the y-value contains this information so there is a quick fix:

```
extract_tree_data <- function(tree_disp, displayorder=TRUE) {
    td_out <- tree_disp$data
    if (displayorder) {
       td_out <- dplyr::arrange(td_out,y)
    }
    return(td_out)
}

extract_tree_data(ggt_reordered) %>% 
    dplyr::filter(isTip) %>% 
    dplyr::pull(label)
```

However, this would not work with other layouts.

Thanks!
Edward

**Comment by brj1** [comment]
The `y$` value will contain the order is circular trees as well.

**Comment by ewallace** [comment]
Could this observation go somewhere useful in the package documentation or bookdown?

**Comment by GuangchuangYu** [comment]
There is a function in `ggtree` to extract tip order, see <http://yulab-smu.top/treedata-book/chapter12.html#tiporder>.
