### ISSUE TITLE
Large tree doesn't look like it's plotted unrooted?

### ISSUE THREAD

**Issue by throwaway123-problems** [YuLab-SMU/ggtree#302]
I used RAxML to generate a large phylogenetic tree with bootstrapped probability measurements.

Files here:
[Archive.zip](https://github.com/YuLab-SMU/ggtree/files/4679705/Archive.zip)

I appended ".nexml" to the RAxML_bipartitionsBranchLabels.T2 file, opened it in dendroscope and saw that it look something like:

<img width="751" alt="Screen Shot 2020-05-25 at 10 59 22 PM" src="https://user-images.githubusercontent.com/65134582/82856214-68b5e900-9edb-11ea-9f07-ad24cb7e1d1d.png">

Which is fine and good enough. So I went ahead and entered the following commands into R to try to open it with ggtree and start generating some better figures using the following:

```
library(ggtree)
library(treeio)

set.seed(1234)

raxml_file <- "./RAxML_bipartitionsBranchLabels.T2"
raxml <- read.raxml(raxml_file)

ggtree(raxml, layout="daylight")


```

But this produces a cladogram tree like:
<img width="568" alt="Screen Shot 2020-05-25 at 11 12 54 PM" src="https://user-images.githubusercontent.com/65134582/82856872-4d4bdd80-9edd-11ea-8d2f-23029eb1813a.png">

Any idea how I can get it to look more like the daylight version? Or the equal distance version that I see via dendroscope?
Not sure if I'm just doing something fundamentally wrong/stupid or it actually isn't possible via ggtree.

Update: tried just the base R plot and got this:
```
library(treeio)
library(ape)

raxml_file <- "~/Desktop/tree_analysis/tree2/RAxML_bipartitionsBranchLabels.T2"
raxml <- read.raxml(raxml_file)
tree_data <- raxml@phylo

plot(tree_data, cex = 1, type='unrooted', edge.width = 0.5, show.tip.label = FALSE,
     lab4ut = 'axial', no.margin = TRUE)

```

<img width="674" alt="Screen Shot 2020-05-26 at 1 31 47 AM" src="https://user-images.githubusercontent.com/65134582/82863702-d15b9080-9ef0-11ea-986a-d6606872d001.png">

**Comment by xiangpin** [comment]
On my computer. I got the figure using `daylight` layout. 
![F1](https://user-images.githubusercontent.com/17870644/82870247-38655d80-9f62-11ea-88d5-4128f372eb5c.PNG)
```
library(treeio)
library(ggtree)

raxml_file <- "./RAxML_bipartitionsBranchLabels.T2"
raxml <- read.raxml(raxml_file)
ggtree(raxml, layout="daylight")
```
Or you can use `equal_angle` layout
```
ggtree(raxml, layout="equal_angle")
```
This produced a tree like:
![F2](https://user-images.githubusercontent.com/17870644/82870275-41eec580-9f62-11ea-8041-30f8d5259cfa.PNG)

**Comment by throwaway123-problems** [comment]
I using a Mac computer. Are you using Windows?
