### ISSUE TITLE
Show AA leters when using msaplot on a phylogeny

### ISSUE THREAD

**Issue by MickAmest** [YuLab-SMU/ggtree#308]
Hello!
 I'd like  to ask if it's possible that, when ploting an AA alignment next to the phylogeny, it shows the aa letters instead of just coloring them? This would be similar to what can be done with the ggmsa package but with a phylogeny.
If it's still not a supported function...are you considering adding it in a future release?

Regards!!

**Comment by brj1** [comment]
You can do this with `ggmsa` and `ggtree` already. Simply add a text layer over top of the msa plot.

```R
library(ggmsa)
library(ggplot2)
protein_sequences <- system.file("extdata", "sample.fasta", package = "ggmsa")

library(Biostrings)
x <- readAAStringSet(protein_sequences)
d <- as.dist(stringDist(x, method = "hamming")/width(x)[1])
library(ape)
tree <- bionj(d)
library(ggtree)
p <- ggtree(tree ) + geom_tiplab()

data = tidy_msa(x, 164, 213)
p + geom_facet(geom = geom_msa, data = data,  panel = 'msa',
               font = NULL, color = "Chemistry_AA") +
    xlim_tree(1) +
   geom_facet(geom = geom_text, data = data, panel = 'msa', mapping = = aes(x = position, label = character))
```

The main problem with this is don't get the nice font from ggmsa. You also may need to adjust the size of the text layer to get the characters right.

**Comment by MickAmest** [comment]
Ok, I will try this. Would be awesome if a function to could be included in the package, though. 
Thank you very much!!

**Comment by Tcvalenzuela** [comment]
I have a question, What is "system.file("extdata", "sample.fasta", package = "ggmsa")" doing?, I can't make it work
I just go around as:

```
library(ggmsa)
library(Biostrings)
library(ggplot2)
library(ape)
library(ggtree)

x <- readAAStringSet("AVP_aa.fas")
d <- as.dist(stringDist(x, method = "hamming")/width(x)[1])

tree <- bionj(d)
reroot_e <- root(phy = tree , outgroup = "Ornithorhynchus_anatinus")

p <- ggtree(reroot_e) + geom_tiplab()
data = tidy_msa(x, 105, 125)
pdf("TreeMSA.pdf")
p + geom_facet(geom = geom_msa, data = data,  panel = 'msa',
               font = NULL, color = "Chemistry_AA") +
  xlim_tree(1) +
  geom_facet(geom = geom_text, data = data, panel = 'msa', mapping = aes(x = position, label = character))
dev.off()
```

**Comment by brj1** [comment]
`system.file("extdata", "sample.fasta", package = "ggmsa")` gets the file name of sample data. However, that sample data is not in the repo any longer, so it does not work. You should just do what you are doing.
