### ISSUE TITLE
Using `gtable` to align plots

### ISSUE THREAD

**Issue by fpbarthel** [YuLab-SMU/ggtree#313]
Hi! I am wondering if it's possible to use the awesome package `gtable` to align ggtree plots to other plots. For some reasons that I haven't been able to narrow down, I cannot get `aplot` to work for my dataset (although it works fine for toy data). 

Here is a toy example using `gtable`. Unfortunately, the alignment is not very good. 

```
library(ape)
library(ggtree)
library(treeio)
library(tidyverse)

set.seed(20200618)

## Create a random tree
tre <- rtree(10)
tre$tip.label <- letters[1:10]

## Build matrix with some random numbers in long format so can be plotted as "heatmap" using geom_tile
gmat <- expand.grid(x = letters[1:10], y = letters[1:10])
gmat$v <- rexp(100, rate=.1)

## Generate some reandom numbres for a line plot
gline <- tibble(x = letters[1:10], y = rnorm(10, 10, 2))

## Generate some random percentages for a bar plot
gbar <- tibble(x = letters[1:10], y = round(runif(10) * 100,1))

## Construct ggtree
gtre <- as_tibble(tre) %>% as.treedata()
ptre <- ggtree(gtre) + geom_tiplab() 

## Highlight some random clade to make the misalignment even more apparent
ptre <- ptre + 
  geom_hilight(node = 12, fill = "tan", alpha = 0.2) + 
  geom_cladelabel(node = 12, label = "Random", angle = 270, hjust = 0.5, offset = 0.05, offset.text = 0.05)

## Extract tip alignment from tree
df <- fortify(gtre) 
df <- subset(df, isTip)
tip_order <- with(df, label[order(y, decreasing=T)])

## Align companion plot data to to tree
gmat <- gmat %>% mutate(x = factor(x, levels = rev(tip_order)), y = factor(x, levels = rev(tip_order)))
gbar <- gbar %>% mutate(x = factor(x, levels = rev(tip_order)))
gline <- gline %>% mutate(x = factor(x, levels = rev(tip_order)))

## Constuct companion plots
pmat <- ggplot(gmat, aes(x,y, fill=v)) + geom_tile()
pbar <- ggplot(gbar, aes(x,y)) + geom_col() + coord_flip()
pline <- ggplot(gline, aes(x,y)) + geom_line(aes(group = 1)) + geom_point() + coord_flip()

## METHOD 1: gtable
library(gtable)
g1 <- ggplotGrob(ptre)
g2 <- ggplotGrob(pmat)
g3 <- ggplotGrob(pbar)
g4 <- ggplotGrob(pline)
g <- cbind(g1,g2,g3,g4)
plot(g)
```

![image](https://user-images.githubusercontent.com/9220167/85065188-c1933d00-b17a-11ea-9365-007a05152be5.png)

**Comment by brj1** [comment]
You could try using the `y` component of the fortified ggtree plot to align the plots better. Also I know this is a toy example - so you may  be coding it differently when you use real data - but when you add the x column to real data you should `merge` it in instead of `mutate` it to make sure the the values are put in the correct column.

**Comment by fpbarthel** [comment]
So the order of the tips is correctly aligned (I am only using `mutate` to change the order of the factor levels, the data is unchanged), there is however a slight discrepancy between the `y` coordinates of the `ggtree` tips when compared to the `geom_tile`, `geom_bar` and `geom_line` plotted alongside of it. 

```
> ggplot_build(ptre)$layout$panel_params[[1]]$y.range
[1]  0.025 10.475
> ggplot_build(pmat)$layout$panel_params[[1]]$y.range
[1]  0.4 10.6
> ggplot_build(pbar)$layout$panel_params[[1]]$y.range
[1]  0.4 10.6
> ggplot_build(pline)$layout$panel_params[[1]]$y.range
[1]  0.4 10.6
```

I am not sure how to get these to line up.

**Comment by fpbarthel** [comment]
Ah! I think I solved this.

```
> ggplot_build(ptre)$layout$panel_params[[1]]$y.range
[1]  0.025 10.475
> ggplot_build(pmat)$layout$panel_params[[1]]$y.range
[1]  0.4 10.6
> ggplot_build(pbar)$layout$panel_params[[1]]$y.range
[1]  0.4 10.6
> ggplot_build(pline)$layout$panel_params[[1]]$y.range
[1]  0.4 10.6
> ptre2 <- ptre + scale_y_continuous(limits = c(0.4,10.6), expand = c(0,0))
> g1 <- ggplotGrob(ptre2)
> g2 <- ggplotGrob(pmat)
> g3 <- ggplotGrob(pbar)
> g4 <- ggplotGrob(pline)
> g <- cbind(g1,g2,g3,g4)
> plot(g)
> ggplot_build(ptre2)$layout$panel_params[[1]]$y.range
[1]  0.4 10.6
```

And now they line up perfectly.

![image](https://user-images.githubusercontent.com/9220167/85086066-a25ed480-b1a7-11ea-8daa-5ef1b0da3163.png)

Hopefully this will help someone else who is trying to use `gtable` for plot alignment since it has a bit more flexibility over using `aplots`

**Comment by GuangchuangYu** [comment]
I recommend you using `aplot` package (examples can be found <https://yulab-smu.top/treedata-book/chapter7.html#composite_plot>).

**Comment by fpbarthel** [comment]
Unfortunately, `aplot` does not work as I mentioned in my initial post. Thank yuo!

**Comment by GuangchuangYu** [comment]
Your example was added in the `aplot` vignette and it works, see <https://yulab-smu.top/pkgdocs/aplot.html>.

**Comment by fpbarthel** [comment]
Yeah that was the oddest thing, it worked fine for the example/toy data, but it never worked for my actual (non-random) phylogenetic data.

**Comment by GuangchuangYu** [comment]
maybe you should try the latest version of aplot (on github)
