### ISSUE TITLE
confusion of function's functionality 

### ISSUE THREAD

**Issue by decenwang** [YuLab-SMU/ggtree#314]
Hi  Dr. Yu

I am reading your "treedata-book", it is really an amazing job.  Anyhow, I got some trouble in the function "groupOTU()" and "groupClade()", chapter 2.2.3.1, [https://yulab-smu.github.io/treedata-book/chapter2.html#tidytree](url).
from my perspective, these two functions can be used to group or display  by grouping. 
"groupClade(as_tibble(tree), c(17, 21))", in this command, the information  "17 and 21" are passed to the function, but I did not understand why is that, in the column "group", there are 0,1,and 2 three classes. I think the parent 17 and 21 should be grouped, and others are grouped into another one. Herein, parent 17 and 21 got different mark "1" and "2", respectively.
```
## # A tibble: 25 x 5
##    parent  node branch.length label group
##     <int> <int>         <dbl> <chr> <fct>
##  1     20     1             4 A     1    
##  2     20     2             4 B     1    
##  3     19     3             5 C     1    
##  4     18     4             6 D     1    
##  5     **17**     5            21 E     **1**    
##  6     22     6             4 F     2    
##  7     22     7            12 G     2    
##  8     **21**     8             8 H     **2**    
##  9     24     9             5 I     0    
## 10     24    10             2 J     0    
## # … with 15 more rows
```
Also, "groupOTU(x, c('t1', 't4'), group_name = "fake_group")"  gave birth to the results:

```
## # A tibble: 7 x 5
##   parent  node branch.length label fake_group
##    <int> <int>         <dbl> <chr> <fct>     
## 1      5     1       0.435   t4    1         
## 2      7     2       0.674   t1    1         
## 3      7     3       0.00202 t3    0         
## 4      6     4       0.0251  t2    0         
## 5      5     5      NA       **<NA>  1**         
## 6      5     6       0.472   **<NA>  1**         
## 7      6     7       0.274   **<NA>  1**
```
Here, t4 and t1 were marked with "1", it is okay, while ,the last <NA> labels were also grouped with "1". I am a little bit confused about these results. Could you help out? Many thanks.

Best,

Decen

**Comment by xiayh17** [comment]
The groupOTU will trace back from input nodes to most recent common ancestor.
The groupClade will trace all immediate descendant clades of internal node you choossing.
