### ISSUE TITLE
Rotating branches causes tip labels rotation in fan plot with an open angle. 

### ISSUE THREAD

**Issue by YiweiZhu** [YuLab-SMU/ggtree#317]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [x] google your question/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)
Hi,
When I rotate branches around a node in a fan plot with an open angle of 90, the tiplabs also rotate unexpectedly. 
Here is a reproducible example. 
`beast_file <- system.file("examples/MCC_FluA_H3.tree", package="ggtree")`
 `beast_tree <- read.beast(beast_file)`
 `p <- ggtree(beast_tree,layout = "fan",branch.length = "none",open.angle = 90)+
  geom_tiplab()`
 `MRCA(beast_tree,1,40)`
 `rotate(p,node = 108)`

![图片](https://user-images.githubusercontent.com/41197115/86087260-5c264100-bad6-11ea-822a-156da087c5db.png)

This issue could be avoided if leaving `open.angle` unset. However, how can I open a 90 degree angle without the tiplabs rotation?

**Comment by xiayh17** [comment]
Hi Yiwei
You just need to use rotate_tree(p,108) instead of rotate(p,node = 108).

**Comment by xiayh17** [comment]
Hi Yiwei


Maybe you can rotate it first and then take the form of fan

p <- ggtree(beast_tree,branch.length = "none")
MRCA(beast_tree,1,40)
p2 <- rotate(p, 108)
p3 <- open_tree(p2, 90)+ geom_tiplab()
p3
