### ISSUE TITLE
object 'mutate.tbl_df' not found

### ISSUE THREAD

**Issue by samlipworth** [YuLab-SMU/ggtree#322]
ggtree seems to have stopped working, I looks like there is an issue with dplyr/tibble compatibility and useing depricated functions

`g<-ggtree(tree)
Error in get(x, envir = ns, inherits = FALSE) : 
  object 'mutate.tbl_df' not found
In addition: Warning messages:
1: `data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: `mutate_()` is deprecated as of dplyr 0.7.0.
Please use `mutate()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. `

**Comment by xiangpin** [comment]
Which version are you using？The newest release version is [`2.2.1`](https://bioconductor.org/packages/release/bioc/html/ggtree.html), some bugs or new functions had been fixed or added. You can see the updated log from [this](https://github.com/YuLab-SMU/ggtree/blob/master/NEWS.md).

**Comment by samlipworth** [comment]
thanks - you are quite right - updating worked (including the nightmare of upgrading my R version to 4, but that's not the fault of ggtree!).
