### ISSUE TITLE
Combining ggtree with gheatmap with a continuous scale using facet_plot

### ISSUE THREAD

**Issue by cms72** [YuLab-SMU/ggtree#331]
### Prerequisites

+ [ x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x ] make sure your are using the latest release version
	* [ x] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [ x] google your question/issue

### Describe you issue

* [ x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ x] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

Hi! I am having issue combining ggtree with gheatmap using facet_plot. I have tried to use the examples in the supp files from https://academic.oup.com/mbe/article/35/12/3041/5142656. But some of the examples aren't working - so its hard for me to figure out what I'm doing wrong.

Basically I have a dataframe:

```
library(data.table)
library(tidyverse)
library(splitstackshape)
library(ggtree)
library(ggplot2)

ID <- c("A1","A2","A3","A4","A5","A6","A7","A8","A9")
Boat  <- c("Green, Blue", "Green", "Blue","Pink, Blue, Green","Blue","Blue, Green","","Pink","Green")
Car <- c("White","White","","","White","","","","White")
Train <-c("Grey","","Grey","Grey","","Grey","Grey","","")
df <-data.frame(ID,Boat,Car,Train)
```

Which I then mutate to create a heatmap
```
df_forggplot<-df %>%
  pivot_longer(cols = -ID, names_to = "Vehicle",  values_to = "Color") %>%
  mutate(Color = str_split(Color, ",")) %>%
  unnest_longer(Color) %>%
  filter(Color != "")
```

And this is the outcome using _**ggplot2**_

```
ggplot(df, aes(x=Color, y=ID))+ #, alpha = Count)) + 
  geom_tile(aes(fill=Vehicle),colour="white",size=0.5)+#, alpha = 1)
  coord_equal()
```

I combine dthis heatmap to my alignment using _**gheatmap**_

This is the alignment (Dummy.aln.treefile)
```
(A1:0.0001589189,((A2:0.0002661836,(((A3:0.0001297835,(A4:0.0016845387,Reference:0.0025983867)100/100:0.0036034778)98.8/96:0.0003588463,A5:0.0004284381)100/79:0.0000868277,A6:0.0002990092)80.7/63:0.0000472130)100/79:0.0000605054,(A7:0.0000383870,A8:0.0000304224)100/100:0.0000228026)100/79:0.0000411939,A9:0.0003248948);
```

And used the following to create the tree using _**ggtree**_
```
file_for_ggtree <- read.tree("~/Dummy.aln.treefile")
midpoint_tree<-midpoint.root(file_for_ggtree)
p<-ggtree(midpoint_tree)
p1 <- p + geom_tiplab(size=3, color="purple")
```

I then mutate my dataframe to suit gheatmap
```
df_forggtree<-cSplit(melt(as.data.table(df), 1), "value", ",", "long")[, dcast(.SD, ID ~ value, value.var = "variable")]
df_forggtree<-data.frame(column_to_rownames(df_forggtree, var = "ID"),check.names = FALSE) #assign ID to rownames for compatibility for gheatmap
```
And this goes as an input for gheatmap -and  it works

```
p2<-gheatmap(p1, df_forggtree, offset=0.000002, width=2, color=NA, colnames=TRUE,colnames_angle = 90, colnames_position= "bottom", font.size = 6 ,colnames_offset_y = 0, hjust = 1)+
  scale_fill_manual(values=c("Boat"="red","Train"="blue","Car"="Green"),
                    breaks=c("Boat","Train","Car"),name="Vehicle")
p2
```

But I would like to add a facet, and have tried to follow the examples in the supp file by doing it this way
```
facet_plot(p1, panel = "Vehicles", data = df_forggplot, geom=geom_tile, mapping = aes(x=Color, fill = Vehicle))
```

But then I get an error saying ```Error: Discrete value supplied to continuous scale```

I am not sure what I am doing wrong, and unfortunately some of the examples in the supp file aren't reproducible. Is this a problem with my dataframe or with facet_plot or is this a feature that hasn't been added to ggtree? I hope you can help.

**Comment by cms72** [comment]
I think I posted in the wrong place - I have moved my issue to google groups :)

**Comment by xiangpin** [comment]
This is because the value of x axis of tree is continuous, but the value of x axis of `geom_tile` is discrete. This is not supported by `facet_grid` of ggplot2. You can set the `Color` column to numeric first.

```
df_forggplot2 <- df_forggplot
df_forggplot2$Color <- factor(df_forggplot2$Color, levels=unique(df_forggplot2$Color))
df_forggplot2$Color <- as.numeric(df_forggplot2$Color)
p3 <- facet_plot(p1, panel = "Vehicles", data = df_forggplot2, geom=geom_tile, mapping = aes(x=Color, y=y, fill = Vehicle))
```
Or you can use `geom_fruit` of [`ggtreeExtra`](https://github.com/YuLab-SMU/ggtreeExtra) to do it.
```
p4 <- p1 + geom_fruit(data=df_forggplot,geom=geom_tile,
                      mapping = aes(y=ID, x=Color, fill=Vehicle),
                      offset=0.1,pwidth=0.5) +
           geom_axis_text(hjust=0,size=6, angle=-90) +
           scale_y_continuous(limits=c(-1, NA))
p4
```
Note: I have remove the blank of color string, the original data contains " Blue" and "Blue", " Green" and "Green".
![pheatmap_test](https://user-images.githubusercontent.com/17870644/88916042-f1645300-d297-11ea-96da-6fbcb7fd04dc.png)

**Comment by cms72** [comment]
Hi xiangpin! Thank you for responding even though I posted it in the wrong area. The ggtreeExtra package looks really good!

**Comment by cms72** [comment]
Hi @xiangpin - just a question. Using facet_plot to combine the heatmap - how do I keep and add the column names to the bottom instead of a legend?

**Comment by cms72** [comment]
@xiangpin , This is what I tried using the code snippet you gave me and the examples from the supp file.

```
df_forggplot2 <- df_forggplot
df_forggplot2$Color <- factor(df_forggplot2$Color, levels=unique(df_forggplot2$Color))
df_forggplot2$Count <- as.numeric(df_forggplot2$Color)
df_forggplot2_df <- unique(select(df_forggplot2, -ID))


p3 <- facet_plot(p1, panel = "Vehicles", data = df_forggplot2, geom=geom_tile, mapping = aes(x=Count, y=y, fill = Vehicle)) %>%
  facet_plot("Vehicles", df_forggplot2_df, geom_text, mapping =aes(x = Count, label = Color), angle = 90)
```

But I keep getting an error

**Comment by xiangpin** [comment]
The description of `facet_plot` (`geom_facet`) has shown it. The first column should be matched with tip label of tree. But you have dropped it. 

```
df_text <- df_forggplot2[!duplicated(df_forggplot2$Count),]
p3 <- facet_plot(p1, panel = "Vehicles", data = df_forggplot2, geom=geom_tile, mapping = aes(x=Count, y=y, fill = Vehicle)) %>%
  facet_plot("Vehicles", df_text, geom_text, mapping =aes(x = Count, label = Color), angle = 90)
```

**Comment by cms72** [comment]
Hi @xiangpin ! Thanks for the reply. I'm getting the following error Error in 
````[[<-.data.frame`(`*tmp*`, ".panel", value = 2L) : 
  replacement has 1 row, data has 0```

**Comment by cms72** [comment]
I restarted R, and ran the script again - but now I'm getting this error 
```Error in rep.int(names(value), lapply(value, length)) : 
  invalid 'times' value```

**Comment by xiangpin** [comment]
The position of `data` and `panel` was reversed.
```
p3 <- facet_plot(p1, panel = "Vehicles", data = df_forggplot2, geom=geom_tile, mapping = aes(x=Count, y=y, fill = Vehicle)) %>%
  facet_plot(data=df_text, panel="Vehicles", geom=geom_text, mapping =aes(x = Count, label = Color), angle = 90)
```

**Comment by xiangpin** [comment]
It have been reproduced on my computer. 

```
df_forggplot2 <- df_forggplot
df_forggplot2$Color <- factor(df_forggplot2$Color, levels=unique(df_forggplot2$Color))
df_forggplot2$xindex <- as.numeric(df_forggplot2$Color)
df_text <- df_forggplot2[!duplicated(df_forggplot2$xindex),]
p3 <- facet_plot(p1, panel = "Vehicles", data = df_forggplot2, geom=geom_tile, mapping = aes(x=xindex, y=y, fill = Vehicle))
p3 <- facet_plot(p3, panel = "Vehicles", data = df_text, geom=geom_text, mapping = aes(x=xindex, y = 0, label = Color), angle = -90)
p3 <- p3 + xlim_tree(max(p1$data$x)+0.5*max(p1$data$x))
```
![pheatmap_test](https://user-images.githubusercontent.com/17870644/88992509-30d18480-d316-11ea-8f21-b3c60bd4a814.png)

**Comment by cms72** [comment]
@xiangpin OMG - You're a legend! It worked. Thank you!
