### ISSUE TITLE
gheatmap with more than two associated matrices - legend issue

### ISSUE THREAD

**Issue by mopratt** [YuLab-SMU/ggtree#335]
When adding multiple associated matrices to gheatmap, as per Chapter 7 (https://yulab-smu.github.io/treedata-book/chapter7.html#gheatmap), the addition of more than one extra matrix leads to an all-black legend for the first heatmap. 
I think this may be an issue with the call to geom_tile() within gheatmap() since **color** is not explicitly mapped within aes() (only **fill** is mapped):
```
p2 <- p + geom_tile(data = dd, aes(x, y, fill = value), 
            width = width, inherit.aes = FALSE)
```
I generated the following figures using consecutive calls to gheatmap() and adding + new_scale_fill() each time, and as you can see in the 3rd figure the legend for "Clade" is all black:

```
h1 <- gheatmap(t3, df, offset = 1, width = 0.1,
               colnames_position = "top",
               colnames_offset_y = 1) +
  scale_fill_viridis_d(option = "D", name = "Clade") + coord_cartesian(clip = "off")
```

![gheatmap_1col](https://user-images.githubusercontent.com/47038455/90830367-2566ed00-e307-11ea-94e5-b1b44dc019ec.png)

```
h2 <- h1 + new_scale_fill()
h3<- gheatmap(h2, df2, offset = 3, width = 0.1,
              colnames_position = "top",
              colnames_offset_y = 1) +
  scale_fill_viridis_d(option = "B", name = "Prov") + coord_cartesian(clip = "off")
```

![gheatmap_2cols](https://user-images.githubusercontent.com/47038455/90830375-27c94700-e307-11ea-9539-f3c41ef1a892.png)

```
h4 <- h3 + new_scale_fill()  

gheatmap(h4, df3, offset = 5, width = 0.1,
         colnames_position = "top", 
         colnames_offset_y = 1) +
  scale_fill_viridis_d(option = "C", name = "Year") + coord_cartesian(clip = "off")
```

![gheatmap_3cols_legend_fix](https://user-images.githubusercontent.com/47038455/90830382-2d269180-e307-11ea-9226-d50a5aca8640.png)

**Comment by GuangchuangYu** [comment]
reproducible example wanted.

**Comment by GuangchuangYu** [comment]
```r
d1 <- data.frame(x = sample(letters[1:4], 10, replace=T))
d2 <- data.frame(y = sample(letters[1:3], 10, replace=T))
d3 <- data.frame(z = sample(letters[2:5], 10, replace=T))

require(ggplot2)
require(ggnewscale)
# install.packages("ggnewscale")
p <- ggplot() + geom_tile(aes(x=1, y=x, fill=x), data=d1)

p1 = p + scale_fill_viridis_d(option = "D", name = "Clade") + 
  coord_cartesian(clip = "off")

p2 = p1 + new_scale_fill() 
p3 <- p2 + geom_tile(aes(x=2, y=y, fill=y), data=d2) +
  scale_fill_viridis_d(option = "B", name = "Prov") + 
  coord_cartesian(clip = "off")
p4 = p3 + new_scale_fill()  
p4 + geom_tile(aes(x=3, y=z, fill=z), data=d3) +
  scale_fill_viridis_d(option = "C", name = "Year") + 
  coord_cartesian(clip = "off")
```

![image](https://user-images.githubusercontent.com/626539/91577370-2ccb6d80-e97b-11ea-8029-5f420dd35cc2.png)

This should be a bug of ggnewscale. It has nothing to do with ggtree.

@eliocamp should be included in this thread.

**Comment by eliocamp** [comment]
This might be related to a bug I introduced in version 0.4.2 that should be fixed in version 0.4.3 (the latest version on CRAN). Using the latest {ggnewscale} I get:

``` r
set.seed(42)
d1 <- data.frame(x = sample(letters[1:4], 10, replace=T))
d2 <- data.frame(y = sample(letters[1:3], 10, replace=T))
d3 <- data.frame(z = sample(letters[2:5], 10, replace=T))

require(ggplot2)
#> Loading required package: ggplot2
require(ggnewscale)
#> Loading required package: ggnewscale
# install.packages("ggnewscale")
p <- ggplot() + geom_tile(aes(x=1, y=x, fill=x), data=d1)

p1 = p + scale_fill_viridis_d(option = "D", name = "Clade") + 
  coord_cartesian(clip = "off")

p2 = p1 + new_scale_fill() 
p3 <- p2 + geom_tile(aes(x=2, y=y, fill=y), data=d2) +
  scale_fill_viridis_d(option = "B", name = "Prov") + 
  coord_cartesian(clip = "off")
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
p4 = p3 + new_scale_fill()  
p4 + geom_tile(aes(x=3, y=z, fill=z), data=d3) +
  scale_fill_viridis_d(option = "C", name = "Year") + 
  coord_cartesian(clip = "off")
#> Coordinate system already present. Adding new coordinate system, which will replace the existing one.
```

![](https://i.imgur.com/6ChonXZ.png)

<sup>Created on 2020-08-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Let me know if this solves the issue.

**Comment by mopratt** [comment]
@eliocamp This fixed it, thank you!

**Comment by araujofarialucas** [comment]
and how to make it when the phylogeny is circular>
