### ISSUE TITLE
`geom_facet()` support discrete scale

### ISSUE THREAD

**Issue by gaospecial** [YuLab-SMU/ggtree#351]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [x] google your question/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

`geom_facet()` is useful when map extra data to a tree object.

```r
library(ggtree)
n <- 20
set.seed(20201120)
tr <- rtree(n)
d1 <- data.frame(id = tr$tip.label,
                 x = sample(1:5, n, replace = TRUE),
                 size = sample(1:5, n, replace = TRUE))
p <- ggtree(tr) + geom_tiplab()
p
```

![image](https://user-images.githubusercontent.com/107597/99771507-37456f80-2b44-11eb-96ef-1fa45b5d0df4.png)

```r
p + geom_facet(aes(x=x,size=size), data = d1, geom = geom_point,panel = "A")
```

![image](https://user-images.githubusercontent.com/107597/99771535-43313180-2b44-11eb-8b8f-91436c5145bc.png)

To date, the `geom_facet()` doesn't support discrete scale.

```r
d2 <- d1
d2$x <- factor(d2$x)
p + geom_facet(aes(x=x,size=size), data = d2, geom = geom_point,panel = "B")
```
run this chunk will report an error:

> Error: Discrete value supplied to continuous scale

Hope Discrete value be supported in the future.

**Comment by GuangchuangYu** [comment]
can't be supported as it is a limitation of ggplot2.

You can:

1. map the discrete value to numeric value before using geom_facet
2. using aplot

**Comment by GuangchuangYu** [comment]
another alternative solution is using ggtreeExtra.

```
 p + geom_fruit(aes(x=x,y=id, size=size), data = d2, geom = geom_point)
```
