### ISSUE TITLE
How to annotate circular trees with "bar_plot"  using ggtree? 

### ISSUE THREAD

**Issue by shelfey** [YuLab-SMU/ggtree#356]
It seems that we can't use  ggtree to annotate circular trees with  "bar_plot" ?   I have read the tutorial carefully ~~~~

**Comment by xiangpin** [comment]
Do you read the vignettes of [ggtreeExtra](https://www.bioconductor.org/packages/release/bioc/vignettes/ggtreeExtra/inst/doc/ggtreeExtra.html) or the Figure 10.2 in [Chapter10](https://yulab-smu.top/treedata-book/chapter10.html#geom-fruit2)?

**Comment by shelfey** [comment]
哇  这是把余叔叔炸出来了嘛？！  哈哈哈  谢谢您～
