### ISSUE TITLE
geom_rootedge() not working as expected when using with scale_x_reverse()

### ISSUE THREAD

**Issue by shunhuahan** [YuLab-SMU/ggtree#357]
Hi,

I noticed that geom_rootedge() is incorrectly positioned when using scale_x_reverse(). Below is the example code to show the problem. Is it a bug related to how geom_rootedge() is implemented? Thank you!

Best Regards,
Shunhua

```
library(ape)
library(ggtree)

test_tree <- rtree(3)
ggtree(test_tree, size = 1) +
  geom_tiplab(offset = -0.05) +
  geom_rootedge(size = 1, rootedge = 1) +
  scale_x_reverse()
```
![image](https://user-images.githubusercontent.com/22645701/102423704-a002f900-3fd7-11eb-9c26-95d5b870aff0.png)

**Comment by xiangpin** [comment]
This issue has been fixed #358
