### ISSUE TITLE
label and unit parameters in geom_treescale 

### ISSUE THREAD

**Issue by GuangchuangYu** [YuLab-SMU/ggtree#359]
<https://groups.google.com/d/msgid/bioc-ggtree/af1e68b0-3db1-4c3b-b793-cc58fc27e81dn%40googlegroups.com?utm_medium=email&utm_source=footer>:

>Hello, 
>
>Is there a way to create a unit label next to the scale bar created using the geom_treescale() function?
>
>Thank you! 

```r
set.seed(2020)
x = rtree(5)
ggtree(x) + geom_treescale(x=2, y=1, offset=.1) + annotate('text', x=2, y=.8, label="substitution rate")
ggtree(x) + geom_treescale(x=2, y=1, offset=-.2) + annotate('text', x=2, y=1.2, label="substitution rate")
```

![image](https://user-images.githubusercontent.com/626539/102839263-0f934100-443b-11eb-9cd5-bb324a04b09f.png)

We should introduce `label` and `offset.label` for labeling something related to the tree scale (e.g. scale unit). 

```
ggtree(x) + geom_treescale(x=2, y=1, offset=.1, offset.label=-.2, label="substitution rate")
ggtree(x) + geom_treescale(x=2, y=1, offset=-.2, offset.label=.2, label="substitution rate")
```
 
The above code should produce the above figure.

Another parameter is unit (default `unit = "native")`, which specify the unit of `x` and `y`. If we passed `unit="npc"`, then the `x` and `y` are relative to the plot panel. 

> npc: Normalised Parent Coordinates (the default). The origin of the viewport is (0, 0) and the viewport has a width and height of 1 unit. For example, (0.5, 0.5) is the centre of the viewport.

**Comment by GuangchuangYu** [comment]
![image](https://user-images.githubusercontent.com/626539/102947809-24d1a380-44ff-11eb-9e32-949d0bd817a2.png)

**Comment by GuangchuangYu** [comment]
@xiangpin In the above figure, the `label` is more close to the line segment. I think we need to set the vjust = 0.5 for labeling `width` and `label`.

**Comment by xiangpin** [comment]
The original `vjust` is `0`. If it is changed to `0.5`, some existing code contained this function (no provide offset) might generate a plot that `line` and `width label` of tree scale can be overlap. Or I set the `vjust` to `vjust <- ifelse(is.null(offset), 0, 0.5)`?

**Comment by GuangchuangYu** [comment]
then keep the source code unchanged and set vjust = 1 for the `label`.

**Comment by GuangchuangYu** [comment]
@xiangpin pls set vjust = 1 for the label by default, so that the amount of offset for the width and label is equal.
