### ISSUE TITLE
Issue with geom_hilight mapping

### ISSUE THREAD

**Issue by hkaspersen** [YuLab-SMU/ggtree#363]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [x] google your question/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

I am having issues when using aesthetic mapping with geom_hilight, as mentioned in issue #326. I cannot reproduce the code, I get the following error when copy-pasting the code from the issue to Rstudio:

```
set.seed(102)
tree <- rtree(60)
p <- ggtree(tree)
#aesthetic mapping
datt <- data.frame(id=c(62, 88), type=c("A", "B"))
p2 <- p + geom_hilight(data=datt,
                        mapping=aes(fill=type, node=id),
                        extendto=7.2) +
  scale_fill_manual(values=c("steelblue", "red"))
```

```
Error in structure(list(node = node, fill = fill, alpha = alpha, extend = extend,  : 
  argument "node" is missing, with no default
```

I am using the newest version of ggplot2 and ggtree, on R version 4.0.2. I was originally trying to use this to hilight multiple nodes in a tree in one go, instead of having to use one geom_hilight per node. If the above doesn't work, is there some other way I can use to do that?

**Comment by GuangchuangYu** [comment]
your ggtree is outdated. This feature is available in newest release.
