### ISSUE TITLE
Column labels are cropped in gheatmap() 

### ISSUE THREAD

**Issue by roey-angel** [YuLab-SMU/ggtree#371]
`gheatmap()` will almost always crop the column labels, regardless of whether they are placed on top or bottom.
This is likely because the plot's margins are set for the tree only.  

- Setting plot using `theme()` does not solve this
- It's possible to bypass it somewhat using the `colnames_offset_y` option but this is sub-optimal because the labels enter the heatmap area.

Example:
```
library(tidyverse)
library(treeio)
library(ggtree)

setwd("./ggtree-master/inst")
beast_file <- system.file("examples/MCC_FluA_H3.tree", package="ggtree")
beast_tree <- read.beast(beast_file)

genotype_file <- system.file("examples/Genotype.txt", package="ggtree")
genotype <- read.table(genotype_file, sep="\t", stringsAsFactor=F)
colnames(genotype) <- sub("\\.$", "", colnames(genotype))
p <- ggtree(beast_tree, mrsd="2013-01-01") + 
  geom_treescale(x=2008, y=1, offset=2) + 
  geom_tiplab(size=2)
gheatmap(p, genotype, offset=5, width=0.5, font.size=3, 
         colnames_angle=-45, hjust=0) +
  scale_fill_manual(breaks=c("HuH3N2", "pdm", "trig"), 
                    values=c("steelblue", "firebrick", "darkgreen"), name="genotype") +
  theme(plot.margin = unit(c(1,1,1,1), "cm"))
```
![Rplot](https://user-images.githubusercontent.com/2523883/106879282-3cde3a80-66db-11eb-88b3-a89f9235ea06.png)

**Comment by ammaraziz** [comment]
If you are still having issues see my comment here:
https://github.com/YuLab-SMU/ggtree/issues/367

**Comment by GuangchuangYu** [comment]
something like `g + ggtree::vexpand(.1, -1)` should works for you, see <https://yulab-smu.top/treedata-book/chapter12.html?q=vexpand#ggexpand>
