### ISSUE TITLE
geom_nodelab() blank for circular trees

### ISSUE THREAD

**Issue by cmt2** [YuLab-SMU/ggtree#374]
I am attempting to add text node labels to a circular phylogeny. When I plot the tree as rectangular, geom_nodelab() works as expected: 

`ggtree::ggtree(example) + ggtree::geom_nodelab(ggplot2::aes(label = anc_state_1))`

![plot_zoom_png](https://user-images.githubusercontent.com/25025386/107707743-72000500-6c66-11eb-8d44-b4c7d8f67da0.png)

However when I set tree layout to circular, it fails to plot text at the nodes. 
`ggtree::ggtree(example, layout = "circular") + ggtree::geom_nodelab(ggplot2::aes(label = anc_state_1))`

![5383e9e9-232f-4e67-bed7-594402d2a7d2](https://user-images.githubusercontent.com/25025386/107707842-9bb92c00-6c66-11eb-8af7-73a387d06746.png)

**Comment by FelixErnst** [comment]
I think you have to use the subset aesthetic in the mapping. It is not mentioned in the man page, but thats how I got it to work.

**Comment by swuyts** [comment]
Hi @cmt2,

I think this has to do with the fact that the circular layout option has changed. If you use `+ layout_circular()` instead of `ggtree(example, layout = "circular")` it seems to work.

Here's a reproducible example:

```
library(ggtree)
set.seed(111)
tree <- rtree(10)

# Rectangular layout => works
ggtree(tree) + geom_nodelab(aes(label = node))
```
![image](https://user-images.githubusercontent.com/12883635/107925066-33bf5a00-6f74-11eb-9d2d-ac2d98f49d98.png)

```
# Circular layout => Does not work
ggtree(tree, layout = "circular") + geom_nodelab(aes(label = node))
```
![image](https://user-images.githubusercontent.com/12883635/107925120-45a0fd00-6f74-11eb-880d-cc7ff9b50446.png)

```
# Circular layout => works
ggtree(tree) + geom_nodelab(aes(label = node)) + layout_circular()
```
![image](https://user-images.githubusercontent.com/12883635/107925147-53568280-6f74-11eb-9ada-6247a0a475b9.png)

**Comment by swuyts** [comment]
Building further on this. How can I get `geom_nodelab` to work again for a daylight visual?

This does not work:
```
ggtree(tree, layout = "daylight") + geom_nodelab(aes(label = node))
```
![image](https://user-images.githubusercontent.com/12883635/107927414-47b88b00-6f77-11eb-9050-420b11fd04d8.png)

What is the `+ layout_circular()` alternative for daylight?

**Comment by brj1** [comment]
You can use `geom_text2()` and `geom_label2()` with the daylight layout.

```R
ggtree(tree, layout = "daylight") + geom_text2(aes(label = node, subset = !isTip))
```
![image](https://user-images.githubusercontent.com/10039876/108280287-d291b500-7132-11eb-8724-909a3da2f201.png)

**Comment by cmt2** [comment]
Thanks all! Seems like using the subset feature with geom_text2 or geom_label2 might be the most stable solution? Ideally this would work across the full range of layout options.

**Comment by GuangchuangYu** [comment]
fixed in <https://github.com/YuLab-SMU/ggtree/pull/353>.
