### ISSUE TITLE
order of tips is not respected while plotting

### ISSUE THREAD

**Issue by FelixErnst** [YuLab-SMU/ggtree#376]
Hi 

This is a refresh of #157

Using the same code as in the original issue with ggtree 2.4.1 results in identical plots

```
library(ape)
set.seed(42)
x <- rtree(5)
y <- ape::rotateConstr(x, c('t1', 't4', 't5', 't3', 't2'))

# original plot
plot(x)

# plot with reordered tips
plot(y)

library(ggtree)
# both ggtree plots appear the same
ggtree::ggtree(x)
ggtree::ggtree(y)
```

Is there an alternative of preserving the plot layout or reordering the plot itself with a similar function to `rotateConstr` in `ggtree`/`tidytree`? Thanks

**Comment by brj1** [comment]
You need to add the `ladderize = FALSE` option as `ggtree` ladderizes by default.

```
ggtree::ggtree(x, laddderize = FALSE)
```

**Comment by FelixErnst** [comment]
😢 

Dang. Should have read the thread more carefully. And the man page. Shame on me!

**Comment by FelixErnst** [comment]
Hi,

the solution with `ladderize = FALSE` gave rise to another problem, which seems to be related to ordering of tips and nodes in combination with conversion of tree objects from tree to tibble to treedata.

With the example tree from the provided file, the following commands produce warnings and/or inconsitant results.

[example_tree.RData.gz](https://github.com/YuLab-SMU/ggtree/files/5975821/example_tree.RData.gz)
```
# Both work
> ggtree(tree, ladderize = FALSE)
> ggtree(tree, ladderize = TRUE)
# Both work and produce the same warning
> ggtree(tidytree::as.treedata(tree), ladderize = FALSE)
Warnmeldung:
Unknown or uninitialised column: `node`.
> ggtree(tidytree::as.treedata(tree), ladderize = TRUE)
Warnmeldung:
Unknown or uninitialised column: `node`. 
```

The warning message can be avoided, when creating a treedata object from a tibble. However, `ladderize=FALSE` will produce an incorrect broken plot.

```
> ggtree(tidytree::as.treedata(tidytree::as_tibble(tree)), ladderize = FALSE)
> ggtree(tidytree::as.treedata(tidytree::as_tibble(tree)), ladderize = TRUE)
```

![image](https://user-images.githubusercontent.com/17824332/107852178-99de9c80-6e0f-11eb-8021-a3a73c3ca291.png)
![image](https://user-images.githubusercontent.com/17824332/107852202-c72b4a80-6e0f-11eb-9688-7329b2f6dfd9.png)

Summary:
- the conversion from tree to treedata is not compatible with ggtree (the node data is missing and gets a warning when plotting)
- the conversion from tree to tibble to treedata is compatible with ggtree, but not lossless, since the `ladderize=FALSE` setting cannot be used.

Since I would like to add data to tree and use it while plotting I am not sure, that there are alternative approaches. I didn't find any getter/setter functions for the `treedata` class, so I assume, the best practice approach to adding data to a tree is to use a `tibble`, which then gets me to a dead end, when I want to use `ladderize = TRUE`.

Thanks for any hints and tips in advance.

**Comment by andzandz11** [comment]
Convert the tips to factors before you make the tree with ordered=T and values=... in the order you want them to be plotted afterwards.

**Comment by FelixErnst** [comment]
Thanks for the comment. Can you elaborate on this? Maybe with an reproducible example? Thanks!
