### ISSUE TITLE
tiplab position flipping

### ISSUE THREAD

**Issue by andzandz11** [YuLab-SMU/ggtree#380]
I use align but the labels are jumping all over the place and even rotating by 180°
My tree has no edge lengths.
Why?
[treesample.zip](https://github.com/YuLab-SMU/ggtree/files/6127110/treesample.zip)

```
load("treesample.load")
pdf(file="Rplot.pdf", width=40, height=40, pointsize=200)

print(ggtree(x, layout='circular', ladderize=F, size=4) + 
  aes(color=log(trait))  +
  scale_color_gradientn(colors=
                          colorRampPalette(
                            c("#BBBBBB", "#BBDF27FF", "#85D44AFF", "#54C568FF", "#2FB47CFF", 
                              "#1FA188FF", "#228C8DFF", "#2A788EFF"),alpha=F)(100) %>% c(.,"#999999"), name="", trans="reverse"
                        ) +
  (
    geom_tiplab(aes(label=label, col=NULL), hjust = -.1, align=T, linesize=1)
  )
)

dev.off()

```

![grafik](https://user-images.githubusercontent.com/19622117/110880184-1e6cef80-82d6-11eb-9605-200fb4288b27.png)

**Comment by andzandz11** [comment]
This may be related to the flipping https://github.com/YuLab-SMU/ggtree/issues/130

**Comment by GuangchuangYu** [comment]
## issue 2

rotating 180° is intended to make the labels more readable.

## issue 1

>labels are jumping all over the place

you should provide reproducible example

**Comment by andzandz11** [comment]
Thank you for your quick reply. I understand the rotation is a good idea now that I printed it out.

What I mean by "jumping" is that the distance of the labels is not equal to the tip. In the example above "Hostaceae" is very close compared to the other labels for example. The difference sometimes is a whole letter of distance.

**Comment by xiangpin** [comment]
This issue has been solved. You can refer to [the request](https://github.com/YuLab-SMU/ggtree/pull/396).
