### ISSUE TITLE
How to remove '0' (root) category when seting colors by taxonomic groups ?

### ISSUE THREAD

**Issue by Mataivic** [YuLab-SMU/ggtree#381]
Hello,

I'm working with a tree of ~200 bacterial species and I set the branches and nodes colors according to their taxonomy (minimal example below)

```
tree <- read.tree('/my/newick/tree.newick')
prepare_tree <- groupOTU(tree, groupInfo)
tree_final <- ggtree(prepare_tree, aes(color=group))
```

The `groupInfo` is simply a list of lists with leaves taxonomy:
```
$Alphaproteobacteria
 [1] "sp1" "sp2" ...
$Bacilli
[1] "sp3" "sp4" ...
$Betaproteobacteria
 [1] "sp5" "sp6" ...
etc ...
```

However, when plotting the tree, one of the two branches starting from the root of is assigned with a color, with the legend '0' (see image below). how can I remove this ?

![tmp](https://user-images.githubusercontent.com/23168771/111183064-cf61db80-85af-11eb-8634-e16d9a6e4c28.png)

**Comment by zhangqingah** [comment]
Do you solve this issue? I have the same problem.
