### ISSUE TITLE
Get Tip Labels by the Rectangular Layout

### ISSUE THREAD

**Issue by neptuneyt** [YuLab-SMU/ggtree#384]
Dear Dr Yu,
Thanks for your amazing work.
My issue is how to get the tree tip labels by the rectangular layout order, eg.:
```
require(ape) 
tr <- rtree(3)
ggtree(tr, layout = 'rectangular') + geom_tiplab()
```
![image](https://user-images.githubusercontent.com/39893798/111986075-6bf42280-8b48-11eb-8f70-373e397203f5.png)
I try to get the tip label of the tree: ```t2, t1, t3```, by tip.label,
```
tr$tip.label
```
just return 
```
[1] "t1" "t3" "t2"
```
I have try to check the ggtree manual, but failed to find some clues.
Looking for your reply, Thanks a lot.

**Comment by brj1** [comment]
The easiest way to do this is to `fortify` the tree. The y column of the resulting tibble is the position in the plot.

```R
require(ape) 
require(dplyr)
tr <- rtree(3)
fort.tr <- fortify(tr) # makes a tibble for plotting ggtree
pull(arrange(filter(fort.tr, isTip), y), label) #reorder and get labels by y position
```

**Comment by neptuneyt** [comment]
Thanks for your reply, but I get below error as your instrcution,
```
require(ape) 
require(dplyr)
tr <- rtree(3)
fort.tr <- fortify(tr) # makes a tibble for plotting ggtree
pull(arrange(filter(fort.tr, isTip), y), label) #reorder and get labels by y position

p.tr <- ggtree(tr) + geom_tiplab()
p.tr$data
```
p.tr$data, return
```
错误: 'data_frame'不是'namespace:vctrs'内的出口对象：
```
and, packaegs version are
```
> packageVersion('ape')
[1] ‘5.4.1’
> packageVersion('dplyr')
[1] ‘1.0.2’
> packageVersion('ggtree')
[1] ‘2.2.4’
```

**Comment by GuangchuangYu** [comment]
This may caused by method/class conflict. 

Load the `conflicted` package may help you detect the issue.

**Comment by GuangchuangYu** [comment]
now we have a `get_taxa_name`, <http://yulab-smu.top/treedata-book/chapter12.html#tiporder>
