### ISSUE TITLE
Error message in geom_cladelab

### ISSUE THREAD

**Issue by megaraptor1** [YuLab-SMU/ggtree#390]
I ran into an unusual error while using the geom_cladelab function. I was trying to plot a continuous trait map with a black outline using the guidelines in the ggtree handbook. Specifically, creating a thin black border around the tree by plotting a slightly wider tree behind it [as suggested in Figure 4.11](http://yulab-smu.top/treedata-book/chapter4.html).

However, when I tried to plot this and adjust the position of the labels, I noticed that if I included a call to vjust, I got an error message saying "Warning: Ignoring unknown parameters: vjust". I checked over the vignette for geom_cladelab and the function said that vjust was a valid parameter.

More concerningly, I have found that I cannot adjust the size of the clade labels plotted by geom_cladelab at all. As you can see in the code below, I have set the size of the clade labels to various sizes, but they end up plotting at the exact same size and their size is unaffected by the size argument. Additionally, I get the following error when I run the code: "Warning: Duplicated aesthetics after name standardisation: size"

```
library(ape); library(tidyverse); library(ggtree);library(curl)
rodent.tree<-read.nexus(curl("https://raw.githubusercontent.com/megaraptor1/mydata/main/engelmanData.tree"))
d<-read.csv(curl("https://raw.githubusercontent.com/megaraptor1/mydata/main/traitdata.csv"))
df<- full_join(rodent.tree, d, by = 'node')
nodes<-c(getMRCA(rodent.tree,tip=c("Idiurus_macrotis","Pedetes_capensis")),getMRCA(rodent.tree,tip=c("Dipus_sagitta","Mus_musculus")),getMRCA(rodent.tree,tip=c("Laonastes_aenigmamus","Cuniculus_paca")),getMRCA(rodent.tree,tip=c("Geomys_pinetis","Castor_canadensis")),getMRCA(rodent.tree,tip=c("Glis_glis","Sciurus_niger")))
ggtree(df,layout="circular",size=2.5)+
  geom_tree(aes(color=trait),continuous=T,size=2)+
  geom_tiplab(color="black",fontface='bold.italic')+
geom_cladelabel(offset=20,size=5,horizontal=FALSE,hjust=0.5,vjust=-0.5,angle="auto",node=getMRCA(rodent.tree,tip=c("Idiurus_macrotis","Pedetes_capensis")),label="Anomaluromorpha",color="red",)+
geom_cladelabel(offset=20,size=7,horizontal=FALSE,hjust=0.5,vjust=0.5,angle="auto",node=getMRCA(rodent.tree,tip=c("Dipus_sagitta","Mus_musculus")),label="Myomorpha",color="blue")+
geom_cladelabel(offset=20,size=3,horizontal=FALSE,hjust=0.5,vjust=-0.5,angle="auto",node=getMRCA(rodent.tree,tip=c("Laonastes_aenigmamus","Cuniculus_paca")),label="Hystricomorpha",color="green")+
geom_cladelabel(offset=20,size=1,horizontal=FALSE,hjust=0.5,vjust=0.5,angle="auto",node=getMRCA(rodent.tree,tip=c("Geomys_pinetis","Castor_canadensis")),label="Castorimorpha",color="orange")+  geom_cladelabel(offset=20,size=7,horizontal=FALSE,hjust=0.5,vjust=-0.5,angle="auto",node=getMRCA(rodent.tree,tip=c("Glis_glis","Sciurus_niger")),label="Sciuromorpha",color="cyan")+
scale_color_gradientn(colours=c("red", 'orange', 'green', 'cyan', 'blue'))+
geom_point2(aes(subset = (node %in% nodes)), color = "black",fill = c("cyan","green","red","blue","orange"), shape = 21, size = 8)
```

### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [X] make sure your are using the latest release version
	* [x] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [X] google your question/issue

### Describe you issue

* [X] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [X] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [X] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

**Comment by xiangpin** [comment]
the `geom_cladelab` and `geom_cladelabel` is different, `geom_cladelab` is an updated version of `geom_cladelabel`, it also supports `aes` mapping. I think you referred to the help of `geom_cladelab`, but you used `geom_cladelabel` in the example. 

and the `EQ` of `geom_tree(aes(color=EQ),continuous=T,size=2)` should be replaced by `trait`, because the `colnames` of `metadata` is `trait`.

**Comment by megaraptor1** [comment]
I have corrected the code to make it replicable as you asked.

I think I also found the problem. Geom_cladlab apparently doesn't accept the arguments size or colour, but separate arguments must be set for font size, font color, and label color.
