### ISSUE TITLE
Error: C stack usage is too close to the limit (with layout="daylight")

### ISSUE THREAD

**Issue by bjmt** [YuLab-SMU/ggtree#400]
Hi,

Starting on the 10th of May my Bioconductor package has been failing the check on the devel branch due to a C stack usage limit error when calling `ggtree` with layout daylight. Running the following code in the Bioconductor devel Docker container is sufficient to trigger the error:

```R
library(ape)
library(ggtree)

rt <- rtree(10)
ggtree(rt, layout = "daylight")
#> Error: C stack usage  7976404 is too close to the limit
```

I hope this can be fixed before the deadline for the next Bioc release -- but if not please let me know so I disable the example.

**Comment by GuangchuangYu** [comment]
according to <https://github.com/YuLab-SMU/ggtree/issues/282>, @xiangpin pls check whether this is caused by the recently [PR](https://github.com/YuLab-SMU/ggtree/pull/394).

**Comment by bjmt** [comment]
I've tried running the example using the latest github version of ggtree, as well as using the latest github versions of ggtree+dplyr. In both cases I still get the error.

**Comment by xiangpin** [comment]
I can run the example using the latest version. I have checked the [PR](https://github.com/YuLab-SMU/ggtree/pull/394). I think it is correct, it used `NextMethod` to inherit the `mutate.data.frame` defined in `mutate.tbl_tree` of `tidytree`.

How about re-install `ggtree` by `remotes::install_github("YuLab-SMU/ggtree")` ? @bjmt

**Comment by bjmt** [comment]
To summarize what I've tried:

- My own local macOS R v4.0 installation + current Bioc 3.12 release version of `ggtree`: no error
- My own local macOS R v4.0 installation + GitHub version of `ggtree`: the error discussed in #395 and #399 (despite my `dplyr` version matching the latest GitHub/CRAN one)
- Bioconductor RELEASE_3_12 docker container + current Bioc 3.12 release version of `ggtree`: no error
- Bioconductor RELEASE_3_12 docker container + current GitHub version of `ggtree`: C stack usage error
- Bioconductor devel docker container + current Bioc 3.12 release version of `ggtree`: no
- Bioconductor devel docker container + current devel version of `ggtree`: C stack usage error
- Bioconductor devel docker container + current GitHub version of `ggtree`: C stack usage error

**Comment by xiangpin** [comment]
Please also update `tidytree` by `remotes::install_github("YuLab-SMU/tidytree")`. This is beacuse the `mutate.tbl_tree` in `tidytree` was not updated in old version.

**Comment by GuangchuangYu** [comment]
I have submitted a new version of `tidytree` to CRAN, hope this helps.

**Comment by bjmt** [comment]
That worked! Thanks a lot, I really appreciate it.

**Comment by gmd2020** [comment]
Updating tidytree was the solution, by running
remotes::install_github("YuLab-SMU/tidytree")

then reloading ggtree

and Voila!

Thanks heaps GuangchuangYu.

**Comment by NicolaiMichael** [comment]
Hi,
While trying to run the code below, I am running into similar issues as outlined above (C stack usage too close to limit) when trying to use "inset". I've tried the suggestions made here (as well as running it on different computers) but I am not getting any positive results. Is this a bug, or might this be the result of running inset on a very big tree (3400 tips)?
Thank you for any help,
**Code:**
tree2 <- full_join(phy, data.frame(label = names(data), stat = data), by = 'label')


p <- ggtree(tree2, layout = "circular")
#create the tree
p1 <- p+geom_tippoint(aes(color = stat),size=5)+scale_color_manual(values = colour)
dev.new()
p2<-inset(p1, pies, width=0.05, height=0.05, hjust=-.06)
