### ISSUE TITLE
after importing consensus raxml tree cannot produce phylogram

### ISSUE THREAD

**Issue by sapuizait** [YuLab-SMU/ggtree#401]
First of all thanks for this amazing package.

Like the title says i cannot produce a phylogram, i can only make cladograms and I am not sure why is this happening.
Here is an example tree that I would like to create a phylogram [https://filebin.net/crszv7jza2fscvlo](https://filebin.net/crszv7jza2fscvlo) 

regardless if i try 

`ggtree(raxml, ladderize=FALSE)`
`ggtree(raxml)`

I keep getting cladograms, does this have to do with the way I produced the consensus tree? But on the other hand i can see that there are phylograms created by a consensus MR raxml tree...

any help will be greatly apprciated

**Comment by xiangpin** [comment]
Because the `edge.length` of your tree contains `NA`.

```
> library(ggtree)
ggtree v2.99.0  For help: https://yulab-smu.top/treedata-book/

If you use ggtree in published research, please cite the most appropriate paper(s):

1. Guangchuang Yu. Using ggtree to visualize data on tree-like structures. Current Protocols in Bioinformatics, 2020, 69:e96. doi:10.1002/cpbi.96
2. Guangchuang Yu, Tommy Tsan-Yuk Lam, Huachen Zhu, Yi Guan. Two methods for mapping and visualizing associated data on phylogeny using ggtree. Molecular Biology and Evolution 2018, 35(12):3041-3043. doi:10.1093/molbev/msy194
3. Guangchuang Yu, David Smith, Huachen Zhu, Yi Guan, Tommy Tsan-Yuk Lam. ggtree: an R package for visualization and annotation of phylogenetic trees with their covariates and other associated data. Methods in Ecology and Evolution 2017, 8(1):28-36. doi:10.1111/2041-210X.12628


> library(treeio)
treeio v1.15.7  For help: https://yulab-smu.top/treedata-book/

If you use treeio in published research, please cite:

LG Wang, TTY Lam, S Xu, Z Dai, L Zhou, T Feng, P Guo, CW Dunn, BR Jones, T Bradley, H Zhu, Y Guan, Y Jiang, G Yu. treeio: an R package for phylogenetic tree input and output with richly annotated and associated data. Molecular Biology and Evolution 2020, 37(2):599-603. doi: 10.1093/molbev/msz240

> tr <- read.raxml("./RAxML_MajorityRuleConsensusTree.RAxML_bootstrap.DeltaProteobacteria_prot_boot_merged.2mr")
> tr@phylo$edge.length
 [1] NaN   1 NaN   1 NaN   1   1 NaN   1 NaN NaN   1 NaN   1 NaN   1 NaN NaN   1
[20] NaN   1 NaN   1 NaN   1 NaN   1 NaN   1 NaN NaN
>
```

**Comment by sapuizait** [comment]
Hey 
Thanks for the help! 
I guess i cannot prevent for some of my trees to have some lengths occasionally missing (this depends on the model and other factors I cannot control - right?) 
but do you think there is a way around it? I mean is there a way to still try and produce a phylogram even though there are some NAs - or do you think it is not worth it and i should stick with the cladogram? (whats your personal opinion?)
Again, thanks!
