### ISSUE TITLE
Unrooted layouts: problems with branch.length and branch annotation

### ISSUE THREAD

**Issue by alephreish** [YuLab-SMU/ggtree#402]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [x] google your question/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

I've been looking into the issue of annotating branches in unrooted layouts and discovered two related problems:

* the `data` tibble of in `ggtree` objects has the `branch` column to be used for the `x` aesthetic as in other layouts, but no analogous hook is available for `y`
* there is apparently a bug that causes the `branch.length` column in the `data` tibble to be out of order.

Consider the following:

    library(ggtree)
    # ggtree v3.1.0
    set.seed(123)
    tree <- rtree(10)
    p <- ggtree(tree, layout = "ape")
    p + geom_nodepoint() + geom_text(aes(label = round(branch.length, 1)), nudge_x = 0.2)

`branch.length` in the `ggtree` object doesn't match the `edge.length` from the original `phylo` object although the actual edge lengths are drawn correctly.

![img1](https://user-images.githubusercontent.com/2794008/119235953-927d0c80-bb3d-11eb-9fe3-1b44b7001ca2.png)

To both, fix `branch.length` and allow placement on the branches, one has to do the following workaround at the moment:

    library(dplyr)
    library(treeio)
    branch.lengths <- as_tibble(tree) %>%
      arrange(node) %>%
      pull(branch.length) %>%
      replace(is.na(.), 0)
    p$data <- p$data %>%
      # fix the branch.length
      mutate(branch.length = branch.lengths[node]) %>%
      # add branch.y for branch's y coordinate
      mutate(branch.y = y - branch.length * sin(angle * pi / 180) / 2)
    p + geom_nodepoint(aes(x = branch, y = branch.y)) + geom_text(aes(label = round(branch.length, 1)), nudge_x = 0.2)

![img2](https://user-images.githubusercontent.com/2794008/119236197-cb69b100-bb3e-11eb-8dd6-3ad698179840.png)

**Comment by GuangchuangYu** [comment]
see also <https://github.com/YuLab-SMU/ggtree/pull/414>.
