### ISSUE TITLE
a new version of geom_nodelab and geom_tiplab

### ISSUE THREAD

**Issue by GuangchuangYu** [YuLab-SMU/ggtree#407]
According to the [PR](https://github.com/YuLab-SMU/ggtree/pull/406), I think the way to determine whether to label internal or external nodes is too tricky and believe we should re-write the `geom_nodelab` and `geom_tiplab`.

The `geom_nodelab` should have a parameter `node = c("all", "internal", "external")` and the default should be "internal" to work as previous version.

The `geom_tiplab` is equivalent to `geom_nodelab(node = "external")`, and `geom_nodelab(node = "all")` is able to add a layer of all labels including internal nodes and external nodes.

**Comment by xiangpin** [comment]
ok，I got it
