### ISSUE TITLE
ggtree build error for upcoming Bioc 3.14

### ISSUE THREAD

**Issue by FelixErnst** [YuLab-SMU/ggtree#413]
Hi,

I use `ggtree` in one of my packages. The build reports for the upcoming Bioc 3.14 (currently in the devel phase) reports an error within `ggtree`.

```
Error in !is.null(data$extendto) && !is.na(data$extendto) : 
  'length(x) = 4 > 1' in coercion to 'logical(1)'
```

http://bioconductor.org/checkResults/devel/bioc-LATEST/miaViz/nebbiolo2-checksrc.html

However, the build reports for `ggtree` itself seems unaffected.

http://bioconductor.org/checkResults/devel/bioc-LATEST/ggtree/nebbiolo2-checksrc.html

Since the error clearly indicates a problem with a logical check within an if statement using a logical vector with a length higher then 1, can you have a look and mabe fix this?

Thanks in advance for any comment and help.

**Comment by FelixErnst** [comment]
@xiangpin @GuangchuangYu I saw that you fixed the issue. Thank you!

Can you push to the Bioc builder to let it propagate through the system? Thanks again!

**Comment by GuangchuangYu** [comment]
already pushed to BioC.

**Comment by FelixErnst** [comment]
Thanks!
