### ISSUE TITLE
Cannot plot bars on tree nodes

### ISSUE THREAD

**Issue by gktahon** [YuLab-SMU/ggtree#416]
Hi all,

First of all, thank you for making such an amazing package like ggtree.
This is not really an issue with the package, rather me having issues getting the result that I want.

I have a phylogenetic tree (see attached) to which I would like to add bars (dodge type) on certain nodes. I have attached a .txt version of the tree. For what I an trying, I have been using the same tree, but in nexus format. 
However, I cannot seem to get the result I need. For testing, I also made a table (tab separated) with in columns 1 and 2 some random data for the bars and in column 3 the node numbers. 

The node numbers I obtained this way:

library(ape)
tree = read.nexus(file="path\to\file")
tree_export = "tree.pdf"
pdf(file=tree_export, width=6, height=6)
plot(tree, cex =0.5, use.edge.length=FALSE)
axisPhylo()
edgelabels(cex = 0.25, width = 0.1)
dev.off()

This gives me the pdf as attached.

Then I want to start adding bars to nodes, the following way, as also explained in the online tutorials:

tree<-read.nexus(file = "nexus.nex")
p<-ggtree(tree)
data<-read.table(file = "test.txt", header = T)
bars <- nodebar(data, cols=1:2, position='dodge', color=c(a='blue', b='red'))
inset(p, bars, x='branch', width=.05, height = 0.07)
print(p)

This adds bars, but for some reason the nodes where they are added don't seem to match the node numbers in the pdf file. So I must be doing something wrong. 

Additionally, I wanted to ask whether there is a way to make my final result more beautiful, like the figures given in https://guangchuangyu.github.io/2016/01/annotate-a-phylogenetic-tree-with-insets/
My final figure is a tree with bars, but the tree is quite condensed and some bars overlap each other, which is not handy.

Thanks a lot for the help, I really appreciate this!
Guillaume

[nexus.pdf](https://github.com/YuLab-SMU/ggtree/files/6717293/nexus.pdf)
[test.txt](https://github.com/YuLab-SMU/ggtree/files/6717582/test.txt)
[nexus.txt](https://github.com/YuLab-SMU/ggtree/files/6717583/nexus.txt)

**Comment by brj1** [comment]
If you run the following code it will show you the node numbers of the internal nodes in ggtree:

```R
ggtree(tree) + geom_nodelab(aes(label=node))
```
