### ISSUE TITLE
Tip labels run off of plot

### ISSUE THREAD

**Issue by alissawilliams** [YuLab-SMU/ggtree#420]
Hello-

I'm having trouble plotting a ggtree. I've included tip labels on the tree, which run off of the end of the pdf file. I've tried resizing the pdf to no avail. 

Here's the code:

```
library(tidyverse)

library(ggtree)

p3tree = read.tree("~/Desktop/dNdS_model1trim_nopoundsigns.nwk")

p = ggtree(p3tree, branch.length = "none") + geom_tree() +  theme_tree()

p = p + geom_tiplab()

pdf("test.pdf")

plot(p)

dev.off()
```

Attached is the resulting plot:

[Rplot.pdf](https://github.com/YuLab-SMU/ggtree/files/6843882/Rplot.pdf)

I've tried lots of different things to fix the issue, including setting the width and height in the pdf command and messing with mar() and par(). The only thing that's made a difference in terms of keeping the entire tip labels on the plot is changing the width, but then I end up with a ridiculously long plot that isn't visible without zooming in a bunch of times. Is there any way to reduce the size of the plot rather than the pdf? Relatedly, is there any way to condense the spacing of the branches in the horizontal direction?

Thanks,
Alissa Williams

**Comment by xiangpin** [comment]
Please refer to [this](https://yulab-smu.top/treedata-book/faq.html#faq-text).
