### ISSUE TITLE
Coloring branches using time-dependent data

### ISSUE THREAD

**Issue by EvoLandEco** [YuLab-SMU/ggtree#425]
Hi,
I don't know if it is proper to ask this question here. I was trying to attach my custom data to a phylo tree, it is easy to attach a heatmap next to the tree, as illustrated below, however, I would like to use edge coloring instead of heatmap to present my custom data, that is, mapping the colors onto the branches, is it possible within ggtree? In my custom data, the x-axis of the heatmap is time and the maximum is identical with tree age.
Thank you in advance.
![image](https://user-images.githubusercontent.com/57348932/128087057-3d0b8b0f-cb47-44fc-a994-c5860dfdd904.png)

**Comment by xiangpin** [comment]
Please provide a reproducible example. Or you can refer to the [example](https://yulab-smu.top/treedata-book/chapter4.html#color-tree) of the [book](https://yulab-smu.top/treedata-book/index.html).
