### ISSUE TITLE
Numbers of left and right parentheses in Newick string not equal

### ISSUE THREAD

**Issue by alienzj** [YuLab-SMU/ggtree#432]
```python
>>> tree = open("tree/tree.nwk").read()
>>> tree.count(")")
203738
>>> tree.count("(")
203738
```

Method 1:
```r
tre <- read.tree("./tree/tree.nwk")
```

Method 2:
```r
tre <- read.newick("./tree/tree.nwk")
```

I got same error when use method 1 or method2.
```
Error in FUN(X[[i]], ...) : numbers of left and right parentheses in Newick string not equal
```

**Comment by alienzj** [comment]
[tree.nwk.txt](https://github.com/YuLab-SMU/ggtree/files/7088952/tree.nwk.txt)

**Comment by brj1** [comment]
The `read.tree` function is exported from the ape package. You should make an issue in ape's GitHub to fix this issue. [https://github.com/emmanuelparadis/ape](https://github.com/emmanuelparadis/ape)

The `read.newick` function in treeio uses ape's `read.tree` function to read the tree, which is why you get the same error.

**Comment by xiangpin** [comment]
This is because the node labels contain ";" symbol, it will be confused with the end of single tree. But I also think it might be a bug of `read.tree` of `ape`. But you can also replace the "; " of node labes to "|" with some tools, such as sed shell or gsub in R.

```
 sed 's\; \|\g' tree.nwk.txt
```

**Comment by alienzj** [comment]
> The `read.tree` function is exported from the ape package. You should make an issue in ape's GitHub to fix this issue. https://github.com/emmanuelparadis/ape
> 
> The `read.newick` function in treeio uses ape's `read.tree` function to read the tree, which is why you get the same error.

Thanks for your answers.

**Comment by alienzj** [comment]
> This is because the node labels contain ";" symbol, it will be confused with the end of single tree. But I also think it might be a bug of `read.tree` of `ape`. But you can also replace the "; " of node labes to "|" with some tools, such as sed shell or gsub in R.
> 
> ```
>  sed 's\; \|\g' tree.nwk.txt
> ```

Nice! Thank you so much~
