### ISSUE TITLE
How to set branch.length="none", as the same time branch length show on the branch

### ISSUE THREAD

**Issue by swmuyu** [YuLab-SMU/ggtree#436]
### Describe you issue
I want to draw a tree following figure (branch.length='none' and branch length show on the branch), but running such code reports an error
![image](https://user-images.githubusercontent.com/65528036/133889145-ceff7d09-2388-49b8-8885-47de5a22b8e4.png)
#============================================
tree <- read.newick("GC00000020.fas.treefile",node.label="support")
p <- ggtree(tree,branch.length="none")+
geom_text(aes(x = branch, label = round(branch.length,2)))
ggsave(p,filename="test.jpg",width=13,height=15)
#============================================
Error in FUN(X[[i]], ...) : object 'branch.length' not found

**Comment by GuangchuangYu** [comment]
```
library(ggtree)
x = rtree(10)
ggtree(x, branch.length='none') + geom_text(aes(x=branch, label=round(branch.length,2)))
```

The above code works.

You need to check your tree file to confirm whether the tree does contain branch length.

**Comment by swmuyu** [comment]
> ```
> library(ggtree)
> x = rtree(10)
> ggtree(x, branch.length='none') + geom_text(aes(x=branch, label=round(branch.length,2)))
> ```
> 
> The above code works.
> 
> You need to check your tree file to confirm whether the tree does contain branch length.

I found the cause of the problem,
p <- ggtree(tree,branch.length="none") This line should be in single quotes
Changing "none" to 'none' can solve my trouble.

Thanks very much for your help.
