### ISSUE TITLE
ggtree different with megaX 

### ISSUE THREAD

**Issue by swmuyu** [YuLab-SMU/ggtree#438]
Hi Prof. Yu.

I use ggtree to draw the nwk file exported from MegaX, but the result displayed by ggtree is similar to MegaX (red arrow).
What is the reason for this? 

![image](https://user-images.githubusercontent.com/65528036/134350196-8264142c-d351-446b-8734-85ca1752f3c8.png)

#============code================
tree <- read.newick(NJ_faa_GC00000018.nwk)
tree$node.label <- round(as.numeric(tree$node.label)*100,1)
p <- ggtree(tree, branch.length='none',size=1, layout = "rectangular") %<+%info+geom_rootedge()+
geom_nodepoint(size=5)+ geom_nodelab(color="#F8F8FF",size=1.8,hjust=0.7)
geom_text(aes(x=branch, label=round(branch.length,2),vjust=-0.8))+
theme(legend.position=c(.1, .85))+theme(plot.title=element_text(size=20,hjust=0.5),legend.title = element_text(size=15,color="black",face="bold"),legend.text = element_text(size=12)) +
geom_tippoint(aes(color=Group),size=7) + scale_color_manual(values=cols)+ xlim(0,25)+
geom_tiplab(aes(color=Group),size=3,offset=0.2)  
ggsave(p,"test.pdf",width=12,height=18)
#============nwk file========================================
((((((((((((((((Ort_Camelpoxvirus_c_:0.00000000,Ort_Camelpoxvirus_m_:0.00000000)0.9800:0.00646960,(Ort_Variola_virus_ma_:0.00161909,Ort_Variola_virus_mi_:0.00010060)0.8550:0.00303334)0.5410:0.00041916,(Ort_Taterapoxvirus:0.00344975,Ort_Vaccinia_virus:0.00000000)0.3480:0.00001000)0.2270:0.00001571,Ort_Horsepoxvirus:0.00343050)0.5170:0.00069251,(Ort_Ectromelia_virus_e_:0.00000000,Ort_Ectromelia_virus_m_:0.00000000)0.9360:0.00448335)0.4250:0.00084950,(Ort_Cowpoxvirus:0.00172015,(Ort_Monkeypoxvirus_c_:0.00344686,Ort_Monkeypoxvirus_z_:0.00000000)0.2820:0.00000251)0.5690:0.00041300)0.4460:0.00108026,Ort_Abatino_macacapoxvirus:0.00212277)0.9230:0.00411000,Ort_Akhmeta_virus:0.00526493)0.9570:0.00689692,(Ort_Volepoxvirus:0.00408670,(Ort_Skunkpoxvirus:0.00991364,Ort_Raccoonpoxvirus:0.00741781)0.6300:0.00283383)0.9960:0.01047448)1.0000:0.03751616,(Cen_Murmansk_microtuspoxvirus:0.01738929,Cen_Yokapoxvirus:0.03553312)1.0000:0.02636392)1.0000:0.06074754,((((Lep_Myxoma_virus_1_:0.00009455,Lep_Myxoma_virus_b_:0.00334779)1.0000:0.01158491,Lep_Rabbit_fibromavirus:0.01104450)1.0000:0.04866638,Ves_Eptesipoxvirus:0.04939935)0.7080:0.01073108,((Cer_Mule_deerpoxvirus:0.04367858,Sui_Swinepoxvirus:0.04427045)0.5930:0.00935996,((Yat_Tanapoxvirus:0.01887491,Yat_Yabamonkeytumor_virus:0.01609369)1.0000:0.04687504,(Ory_Cotia_virus:0.08581739,(Cap_Sheeppoxvirus:0.00960756,(Cap_Lumpy_skindisease_virus:0.00209324,Cap_Goatpoxvirus:0.00480334)0.4630:0.00078672)1.0000:0.04818813)0.3080:0.00460736)0.1750:0.00139371)0.4960:0.00794364)0.9410:0.01917352)0.8590:0.01736014,((Pte_Pteropoxvirus:0.10373309,Mus_Sea_otterpoxvirus:0.08687009)1.0000:0.04485413,(Par_Greysealpoxvirus:0.03577019,((Par_Bovinepapularstomatitis_virus:0.03562194,Par_Reddeerpoxvirus:0.02639971)0.5990:0.00549814,(Par_Pseudocowpoxvirus:0.01164841,(Par_Orfvirus_o_:0.00348617,Par_Orfvirus_n_:0.00341041)0.9920:0.01101445)1.0000:0.02951377)0.8250:0.00914613)1.0000:0.16360320)0.7410:0.01851780)0.2420:0.00207522,Sci_Squirrelpoxvirus:0.11188145)0.5300:0.01615287,(((Mac_Eastern_kangaroopoxvirus:0.00000000,Mac_Western_kangaroopoxvirus:0.00000000)1.0000:0.06247284,Mol_Molluscum_contagiosumvirus:0.05595474)0.9930:0.03211602,(Avi_Turkeypoxvirus:0.05908303,(Avi_Canarypoxvirus:0.03653497,(Avi_Fowlpoxvirus:0.00491643,(Avi_Penguinpoxvirus:0.00209651,(Avi_Pigeonpoxvirus:0.00180398,Avi_Flamingopoxvirus:0.00163836)0.6110:0.00135178)0.9540:0.00547033)1.0000:0.02428863)0.8180:0.00930251)1.0000:0.07873346)0.8560:0.02282593)0.7860:0.02730299,(Cro_Nile_crocodilepoxvirus:0.00421986,(Cro_saltwater_crocodilepoxvirus_1_:0.00000000,Cro_saltwater_crocodilepoxvirus_2_:0.00000000)1.0000:0.01486138)1.0000:0.17918381)1.0000:0.20065994,Sal_Salmongillpoxvirus:0.46520428,(Del_Melanoplus_sanguinipesentomopoxvirus:0.23401324,(Alp_Anomala_cupreaentomopoxvirus:0.15885079,((Bet_Mythimna_separataentomopoxvirus:0.04236215,Bet_Adoxophyes_honmaientomopoxvirus:0.04934627)0.4590:0.00466469,(Bet_Amsacta_mooreientomopoxvirus:0.05055090,(Bet_Choristoneura_biennisentomopoxvirus:0.01161749,Bet_Choristoneura_rosaceanaentomopoxvirus:0.00746375)1.0000:0.03539228)0.4870:0.00553314)1.0000:0.13202398)1.0000:0.09445416)1.0000:0.30397703);

**Comment by GuangchuangYu** [comment]
![image](https://user-images.githubusercontent.com/626539/134844111-489ba73e-2c6e-4502-a60f-897c0f939ff9.png)

you should know that clade can be rotated.
