### ISSUE TITLE
geom_tippoint - increasing space between points

### ISSUE THREAD

**Issue by KatDawkins** [YuLab-SMU/ggtree#440]
I first created a tree using phyloseq but I needed to make this tree into a fan-shape, so I am editing it using ggtree.  This is the phyloseq tree (not built on real data, but just for testing purposes).

![image](https://user-images.githubusercontent.com/91240226/134456560-226db5b3-41a1-447c-a779-056bc4455397.png)

To make this same tree but in a fan-layout using ggtree, I have used the following code:

>p <- ggtree(physeq, ladderize = TRUE, layout="fan", open.angle=120) +
geom_tiplab(aes(label=Family), hjust=-.5, size=3)+
geom_tippoint(aes(x=x+hjust, color=Location) , size=3, na.rm=TRUE)+
scale_size_continuous(trans=log_trans(5))+
theme(legend.position="right")

However, the tree that is produced has overlapped the tippoints.

![image](https://user-images.githubusercontent.com/91240226/134457019-f6fbcc4d-6d2a-4257-8a32-445b9e98f10d.png)

How do I increase the spacing between the points?

Thanks in advance!

**Comment by brj1** [comment]
Just multiply `hjust` in the mapping (`aes()`) of `geom_tippoint` by something. For example:

```R
p <- ggtree(physeq, ladderize = TRUE, layout="fan", open.angle=120) +
geom_tiplab(aes(label=Family), hjust=-.5, size=3)+
geom_tippoint(aes(x=x+2*hjust, color=Location) , size=3, na.rm=TRUE)+ \\ hjust changed to 2*hjust
scale_size_continuous(trans=log_trans(5))+
theme(legend.position="right")
```

**Comment by KatDawkins** [comment]
You're a legend - thank you so much!  My problem now is that the tip labels don't align neatly with the tips of the tree - they should essentially follow on from the coloured dots. I don't suppose you know how to adjust this?

![image](https://user-images.githubusercontent.com/91240226/135183439-32804918-ae86-45bc-94d5-351097149470.png)
