### ISSUE TITLE
geom_tiplab gives an error in Shiny despite using github version

### ISSUE THREAD

**Issue by gauravdiwan89** [YuLab-SMU/ggtree#442]
Hello,

The issue #404 has popped back up again despite using the github version.

Can you please help?

_Originally posted by @gauravdiwan89 in https://github.com/YuLab-SMU/ggtree/issues/404#issuecomment-930258366_

**Comment by xiangpin** [comment]
I can run the [example] #404  using the `github` version, please provide more detail information about the problem.

**Comment by gauravdiwan89** [comment]
Thanks for the reply. Well, it looks like it started working for me too! Sorry about that
