### ISSUE TITLE
Problems installing ggtree with rvcheck 0.2.0

### ISSUE THREAD

**Issue by Juanphg** [YuLab-SMU/ggtree#447]
Hello,
I'm having a problem installing ggtree running R 3.6 on Linux mint 20.  I wrote to Bioconductor ([here](https://github.com/Bioconductor/BiocManager/issues/64)), showing the error and they suggested that I should downgrade rvcheck to a version lower than 0.2.0. I did it to version 0.1.3 and I was able to apparently install ggtree. Initially I tought it worked, because it was shown in the package panel in Rstudio. Nevertheles, when I try to load it I get the following message: 
```
> library(ggtree)
Error: package or namespace load failed for ‘ggtree’:
 object ‘get_aes_var’ is not exported by 'namespace:rvcheck''
```
Thanks for your help,
Cheers, 
Juan P.

**Comment by GuangchuangYu** [comment]
you need to restart your R if rvcheck 0.1.3 was installed successfully.

Otherwise, you did not manage to install it successfully.

**Comment by GuangchuangYu** [comment]
I would suggest you to upgrade your R and install the latest release version of ggtree, which contains many important features.
