### ISSUE TITLE
Library fails to load

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [YuLab-SMU/ggtree#448]
Hi,

I have searched for answers to this problem but found none. Apologies if it is something simple.

I am using R v4.0.4 in R studio for Windows. I installed ggtree with:
BiocManager::install("ggtree",force=TRUE)

Then get this error:

library("ggtree")
Error: package or namespace load failed for ‘ggtree’:
 object ‘get_aes_var’ is not exported by 'namespace:rvcheck'
In addition: Warning message:
package ‘ggtree’ was built under R version 4.0.5 

Thanks,

T.

**Comment by ShixiangWang** [comment]
I just got same issue. Roll back version to v0.1.8 would work

```
install.packages("https://cran.r-project.org/src/contrib/Archive/rvcheck/rvcheck_0.1.8.tar.gz", repos = NULL)
```

**Comment by DIAODIAODA** [comment]
`install.packages("https://cran.r-project.org/src/contrib/Archive/rvcheck/rvcheck_0.1.3.tar.gz", repos = NULL)`
quit and restart your R， use `BiocManager::install("ggtree",force=TRUE) ` again, you will find it works
