### ISSUE TITLE
ggtree+groupOTU legend's issue

### ISSUE THREAD

**Issue by Zilong-Li** [YuLab-SMU/ggtree#455]
The line in legend of my plot looks strange when I added `+geom_tiplab()`. Do you have any idea about it?

`t2 <- tree %>%
  ggtree(layout = "circular", branch.length = "none") %>%
  groupOTU(lpps, "Pops") + aes(color = Pops) + scale_color_manual(values = mycol) + theme(legend.position = "right") + geom_tiplab(size = 3)`

![image](https://user-images.githubusercontent.com/11785793/143866559-aa5b207a-fc54-4598-810f-ccf3e7fb1e83.png)

**Comment by xiangpin** [comment]
you can use geom_tiplab(show.legend=FALSE) to mask the legend of text layer.

**Comment by Zilong-Li** [comment]
@xiangpin Many thanks! it works. You are fast 😉
