### ISSUE TITLE
plot error?

### ISSUE THREAD

**Issue by Hongjinwu** [YuLab-SMU/ggtree#457]
I suspect an error in ggtree(v3.0.0), but not sure.  my issue is that, I have a nhx tree with every node has an attribute "T" or "F". root node and tips are always "T". I try to plot the tree and color the nodes("T":blue, "F":red), but I have got some tips red, and I check the attribute of the tips and find that they are "T". So, red tips is wrongly colored. I suspect if there is a confliction between traverse orders? 
my code:

library(ggplot2)
library(treeio)
library(ggtree)
library(cowplot)
options(scipen=999)
args=commandArgs(T)

filename <- commandArgs(trailingOnly = T)[1]
for (i in seq(1,1)){
	tr_inf   <- read.nhx(paste0(filename,".nhx"))
	compares <- tr_inf@data$Compare      #compare is "T" or "F"
	p_inf    <- ggtree(tr_inf, branch.length='none') + geom_tiplab(hjust = 0.5, vjust = 1, size = 3,offset=-0.1)  + coord_flip() + scale_x_reverse() + ggtitle("Inferred clonal frame") + theme(plot.title = element_text(size = 10))+geom_label(label='',aes(fill=compares),alpha=1, colour = "black",size = 3)
	ggsave(plot = p_inf, width = 15, height = 10, filename = paste0(filename,".png"))
}

**Comment by xiangpin** [comment]
I think your codes might generate errors. The `compares` might be a vector from the `tr_inf` which is a treedata class. However, it might be used directly in the `geom_label`. I think you want to map the `Compare` of `tr_inf` to the color of `label`. But, your codes do not conform to the syntax of `ggplot2`.

```
library(ggtree)
library(magrittr)
set.seed(10)
tree <- rtree(10)
dat <- data.frame(id=tree$tip.label, Compare=rep(c("T", "F")))
tree %<>% dplyr::left_join(dat, by=c("label"="id"))
tree
tree %>% 
  ggtree(layout="dend") + 
  geom_tiplab(
      mapping=aes(fill=Compare), 
      hjust=.5, 
      vjust = 1, 
      geom="label")
```

![xx](https://user-images.githubusercontent.com/17870644/144428064-204a0a69-1711-490f-b8b5-508d13060737.PNG)

**Comment by Hongjinwu** [comment]
I want to plot not only the tips, but all the node. like this
![test](https://user-images.githubusercontent.com/62492420/144533293-93800d4a-a5bc-4155-834e-eea1769c8d4d.png)
[test.nhx.txt](https://github.com/YuLab-SMU/ggtree/files/7646347/test.nhx.txt)

In the plot some tips and root node is colored with red(F). but nhx tree(see attachment test.nhx.txt) tips and root is always blue("T"). so I use python package ete3 to check if the Compare attribute of root is "T" or "F". result is:
>>> import ete3
>>> t=ete3.Tree("test.nhx")
>>> t.Compare
'T'

it's "T", but is assign "F" to the root in the plot. so I suspect the nodes are incorrectly colored. 

my modified code is:
library(ggplot2)
library(treeio)
library(ggtree)
library(cowplot)
options(scipen=999)
args=commandArgs(T)

filename <- commandArgs(trailingOnly = T)[1]
tr_inf   <- read.nhx(paste0(filename,".nhx"))
compares <- tr_inf@data$Compare
p_inf    <- ggtree(tr_inf, branch.length='none') + geom_tiplab(hjust = 0.5, vjust = 1, size = 3,offset=-0.1)  + coord_flip() + scale_x_reverse() + ggtitle("Inferred clonal frame") + theme(plot.title = element_text(size = 10))+geom_nodelab(mapping=aes(fill=compares,label=compares),alpha=1, colour = "black",size = 3,geom="label")
ggsave(plot = p_inf, width = 15, height = 10, filename = paste0(filename,".png"))

**Comment by xiangpin** [comment]
Your codes are incorrect. The `Compare` variable should be directly mapped to the `aesthetic` of `geom`.

```
library(ggtree)
library(ggplot2)
library(treeio)
tr.da <- read.nhx("./test.nhx.text")
tr.da
tr.da %>% dplyr::filter(isTip, keep.td=F) %>% dplyr::pull(Compare)
tr.da %>% 
     ggtree(layout="den", branch.length="none") + 
     geom_nodelab(
          mapping=aes(fill=Compare, label=Compare), 
         geom="label", node="all", size=3
      )
```
![xx](https://user-images.githubusercontent.com/17870644/144537695-e0fb7799-4a4e-4db5-9beb-f00709cddc0c.PNG)

```
# Or using geom_label
tr.da %>% ggtree(layout="den", branch.length="none") +
      geom_label(
          mapping = aes(label = Compare, fill = Compare),
          size = 3
       )
```
![xx2](https://user-images.githubusercontent.com/17870644/144537723-6eda7bee-7159-4cda-ab15-856fcb270b14.PNG)

**Comment by Hongjinwu** [comment]
OK Thanks very much for the help!
