### ISSUE TITLE
Two tree like pheatmap

### ISSUE THREAD

**Issue by yjiakang** [YuLab-SMU/ggtree#462]
Hi, I have searched the issues, and did not get idea on how to add two trees in a heatmap. That is to say, is it possible to add a tree at the top of the heatmap after adding a tree at the left side of a matrix at the same time. Just like the hclust did in the heatmap. Thanks in advance.
![image](https://user-images.githubusercontent.com/49177016/145676104-5b555969-fe14-401a-ab21-8ce705242b14.png)

**Comment by GuangchuangYu** [comment]
maybe you can try the `aplot` package.

**Comment by yjiakang** [comment]
Yeah，thanks！The package worked.
