### ISSUE TITLE
Daylight layout error with labelling collapsed node

### ISSUE THREAD

**Issue by AroneyS** [YuLab-SMU/ggtree#466]
Firstly, thanks for your incredibly useful package!
I have been trying to produce a daylight-layout tree with collapsed clades. I get an error, however, when I try and add a cladelabel to a collapsed clade. This error does not occur in a standard-layout tree.

In addition, as seen in p2, the size and angle of the "mixed" triangles of a collapsed clade in a daylight-layout tree seems off. For example, compare p2 (below), to the same tree and clade collapse in iTOL. Any suggestions?

```r
nwk <- system.file("extdata", "sample.nwk", package = "treeio")
tree <- read.tree(nwk)
p <- ggtree(tree) %>%
  collapse(node = 21, "mixed") +
  geom_cladelab(node = 21, label = "test")

p2 <- ggtree(tree, layout = "daylight") %>%
  collapse(node = 21, "mixed")

p3 <- ggtree(tree, layout = "daylight") %>%
  collapse(node = 21, "mixed") +
  geom_cladelab(node = 21, label = "test")
```

Output from p3:
```
Average angle change [1] 0.161786714463209
Average angle change [2] 0.050721258810625
Average angle change [3] 0.0238174251191971
Error in if (delta > 1) { : missing value where TRUE/FALSE needed
```
Expected: produce same tree with collapsed clade labelled with "test"

p2 tree:
![image](https://user-images.githubusercontent.com/41124903/148475817-33d59e0a-f6de-4f17-a9a7-42d6ea95fc1e.png)

iTOL tree:
![image](https://user-images.githubusercontent.com/41124903/148475686-6d05e3a8-0864-46a7-a153-34565c330af7.png)

### Prerequisites

+ [ ] Have you read [Feedback](https://guangchuangyu.github.io/ggtree/#feedback)
Above is deadlink.
+ [x] and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://yulab-smu.github.io/treedata-book/)
	* [x] google your question/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [google group](https://groups.google.com/forum/#!forum/bioc-ggtree)

**Comment by xiangpin** [comment]
The `collapse` will be optimized, But now I think you can adjust the order of `geom_cladelab` and `collapse` for `daylight` layout.

```
library(ggtree)
nwk <- system.file("extdata", "sample.nwk", package = "treeio")
tree <- read.tree(nwk)
p2 <- (ggtree(tree, layout = "daylight") + geom_cladelab(node = 21, label = "test", angle="auto")) %>% 
          collapse(node = 21, "max")
p2
```
![xx](https://user-images.githubusercontent.com/17870644/148767714-ff432c32-31b7-4271-b526-4f9536266c77.PNG)

**Comment by AroneyS** [comment]
Thanks for your response. The solution works for me.

I am a bit confused as to why the collapsing nomenclature has switched for the daylight layout. 
That is, why does a "max" collapse look liked it is "mixed" and visa versa? Also what is going on with the "min" option?
