### ISSUE TITLE
how to add a gradient backgroud?

### ISSUE THREAD

**Issue by felixlee0608** [YuLab-SMU/ggtree#467]
like fig2b
[tree](https://www.nature.com/articles/s41586-019-1852-5/figures/2)

**Comment by xiangpin** [comment]
You can refer to the example of the [request](https://github.com/YuLab-SMU/ggtree/pull/449). Now, the gradient highlight only supports for Linux platform. We suggest you can read the manual of `geom_hilight` via `?geom_hilight`.

```
library(ggplot2)
set.seed(102)
tree <- rtree(60)
p <- ggtree(tree)
dat <- data.frame(id=c(62, 88), type=c("A", "B"))
x1 <- p + geom_hilight(
       data = dat, 
       mapping = aes(node=id, fill=type), 
       type = "gradient", 
       gradient.direction="tr", 
       alpha=0.68,
       extend = .5
     )
# Or you can put the geom_hilight to the front of geom_tree.
x2 <- ggplot(tree) + 
geom_hilight(
    data=dat, 
    mapping=aes(node=id, fill=type), 
    type = "gradient", 
    gradient.direction="tr", 
    alpha=0.68,
    extend=.5
) + 
geom_tree() + 
theme_tree()
x1 + x2
```
![xx](https://user-images.githubusercontent.com/17870644/148766008-a5a434e9-1b82-47fb-bf7c-20cf5876139e.PNG)

**Comment by felixlee0608** [comment]
the same code,but the different figure! there is no backgroud.

>  packageVersion('ggtree')
[1] ‘3.3.1’

@xiangpin 

![image](https://user-images.githubusercontent.com/33302799/148769003-f73d88b2-d34b-4e86-9d41-ceb42b69fc87.png)

**Comment by xiangpin** [comment]
> Now, the gradient highlight only supports for Linux platform

This is the issue of graphics devices on windows or mac. Maybe you can use `svg` to generate the figure

```
svg("test.svg")
target_figure_ggtree_object
dev.off()
```

**Comment by felixlee0608** [comment]
> > Now, the gradient highlight only supports for Linux platform
> 
> This is the issue of graphics devices on windows or mac. Maybe you can use `svg` to generate the figure
> 
> ```
> svg("test.svg")
> target_figure_ggtree_object
> dev.off()
> ```

Got it! Thanks
