### ISSUE TITLE
Error: ! Can't subset `.data` outside of a data mask context.

### ISSUE THREAD

**Issue by KyleTDavid** [YuLab-SMU/ggtree#486]
Hello,

I receive the above error whenever I try `ggtree()` for example:
>data(chiroptera, package="ape")
ggtree(chiroptera)

or
>ggtree(read.tree(text ='((t2:0.04,t1:0.34):0.89,(t5:0.37,(t4:0.03,t3:0.67):0.9):0.59);'))

I'll attach the full error and my session info below, any idea what might be going on?

[error_message.txt](https://github.com/YuLab-SMU/ggtree/files/8162438/error_message.txt)
[session_info.txt](https://github.com/YuLab-SMU/ggtree/files/8162437/session_info.txt)

**Comment by GuangchuangYu** [comment]
see also <https://github.com/YuLab-SMU/ggtree/issues/399>.

**Comment by KyleTDavid** [comment]
reverting back to dplyr 1.0.5 got the job done, thanks!

**Comment by astaroph** [comment]
I hate to throw a wrench in the works, but I have run into this issue and reverting to dplyr 1.0.5 does not work anymore. When I try to revert to 1.0.5, the version of ggtree I am using (2.4.2) will no longer even load, and says it requires dplyr 1.0.10 at least, but I still get this cant subset .data outside of a data mask context error if I try any later version of dplyr.
I'm using R 4.0.3 and bioconductor 3.12 for compatibility reasons and would prefer not having to update every single one of my other packages right at this moment to switch to the most current version, so any help would be appreciated.

**Comment by oushujun** [comment]
@astaroph I had the same issue. this helped me out: https://github.com/YuLab-SMU/ggtree/issues/625#issuecomment-2287708047
