### ISSUE TITLE
Problems with ggtree and treeio

### ISSUE THREAD

**Issue by cabraham03** [YuLab-SMU/ggtree#495]
Hi, I have problem when I load a file, it stay in " 1: "

```
beast_file <- system.file("plotTree-master/examples/MCC_FluA_H3.tree", package="ggtree")
read.beast(beast_file)
```

the result is in the picture: 

![Screen Shot 2022-04-26 at 1 08 29 PM](https://user-images.githubusercontent.com/9662585/165374723-956943f4-ca37-40c9-9bbb-2f59b993e816.png)

Any help !!
Thanks

**Comment by GuangchuangYu** [comment]
https://yulab-smu.top/treedata-book/faq.html#faq-local-file
