### ISSUE TITLE
Slanted layout v2

### ISSUE THREAD

**Issue by brunomioto** [YuLab-SMU/ggtree#496]
It would be nice to have a new slanted layout based on what is used in other software

ggtree slanted layout: 
![image](https://user-images.githubusercontent.com/10459392/165532991-1e6d6420-61d2-4a7f-8877-59fd88ed6345.png)

A simpler and more familiar form:
![image](https://user-images.githubusercontent.com/10459392/165532831-2f3e22f8-bb31-4f89-b9b6-c6c6c8c93b11.png)

**Comment by GuangchuangYu** [comment]
see <https://github.com/YuLab-SMU/ggtree/pull/497>.
