### ISSUE TITLE
rename tip label by a mapping table for multiphylo tree

### ISSUE THREAD

**Issue by neptuneyt** [YuLab-SMU/ggtree#500]
Dear Dr Yu,
Thanks for your such amazing work.
My issue is that, Suppose I have a newick file A, and a list of old and new names mapping table B, how do I replace these names at once and keep remains still?
* A.newick
```
(a:0.2,b,c,d);
(a:0.3,b,c,d);
```
* B.csv
```
old,new
a,A
c,C
d,D
```
The result should be like:
```
(A:0.2,b,C,D);
(A:0.3,b,C,D);
```
Thanks a lot!

**Comment by GuangchuangYu** [comment]
[duplicated](https://github.com/YuLab-SMU/treeio/issues/79)
