### ISSUE TITLE
安装ggtree咋还需要yulab.utils？

### ISSUE THREAD

**Issue by wangshun1121** [YuLab-SMU/ggtree#501]
如下图：

<img width="992" alt="image" src="https://user-images.githubusercontent.com/16040615/168524686-47719de2-7b99-4312-a87d-2f3524abad3e.png">

从bioconductor上装这个包，怎么还要依赖yulab.utils？

**Comment by GuangchuangYu** [comment]
`install.packages("yulab.utils")`

**Comment by GuangchuangYu** [comment]
`install.packages("yulab.utils")`

**Comment by wangshun1121** [comment]
好吧，我真没有想到这个包居然能在cran上榜上有名
