### ISSUE TITLE
Limit BEAST 95% HPD node date estimates for geom_range plotting of error

### ISSUE THREAD

**Issue by ksw9** [YuLab-SMU/ggtree#515]
### Prerequisites
Hi,

Thank you for a fantastic resource. 

I'm plotting BEAST MCC trees, following your [book](https://yulab-smu.top/treedata-book/chapter5.html?q=geom_range#uncertainty-of-evolutionary-inference). 
I am wondering if you could suggest how to (1) only plot error bars for internal nodes (not tips) and (2) limit the error bar ranges to the most recent date of sampling? For example, the error bars in recent nodes frequently extend beyond the most recent sampling date, which of course is not possible.

I am plotting a time-scaled Bayesian MCC tree with the following:

```
# Plot
p <- p + theme_tree2() + # scale bar
  scale_x_ggtree(breaks = seq(1500,2000, by = 100))  # rescale x-axis for BEAST 

# Plot with error bars
p1 <- p + 
  geom_range(range='length_0.95_HPD', color='grey', alpha=.6, size=2)
```
Thank you in advance and all the best.

**Comment by brj1** [comment]
I think you want to use 'height_0.95_HPD', not 'length_0.95_HPD'. 'height_0.95_HPD' records the heights (time before most recent sample) of the nodes and 'length_0.95_HPD' records the branch lengths of the parent branches of the nodes.

**Comment by GuangchuangYu** [comment]
Thanks @brj1 . The book is now in printing, and we can only update the example for the next edition.

**Comment by ksw9** [comment]
Perfect, thank you very much for the quick responses @brj1 and @GuangchuangYu! Thank you again for a fantastic resource!
