### ISSUE TITLE
Error install ggtree R4.1.3

### ISSUE THREAD

**Issue by Kirito-Ma** [YuLab-SMU/ggtree#519]
I tried to install the ggtree by this code:
BiocManager::install("ggtree")

However, it showed me the error like this:
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.14 (BiocManager 1.30.18), R 4.1.3 (2022-03-10)
Installing package(s) 'ggtree'
trying URL 'https://bioconductor.org/packages/3.14/bioc/src/contrib/ggtree_3.2.1.tar.gz'
Content type 'application/x-gzip' length 344549 bytes (336 KB)
==================================================
downloaded 336 KB

* installing *source* package ‘ggtree’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
**Error in get(x, envir = ns, inherits = FALSE) : 
  object 'warning_wrap' not found**
Error: unable to load R code in package ‘ggtree’
Execution halted
ERROR: lazy loading failed for package ‘ggtree’
* removing ‘/stornext/Home/data/allstaff/m/ma.m/R/x86_64-pc-linux-gnu-library/4.1/ggtree’

The downloaded source packages are in
	‘/vast/scratch/users/ma.m/Rtmp/RtmpAeDfOY/downloaded_packages’
Installation paths not writeable, unable to update packages
  path: /stornext/System/data/apps/R/R-4.1.3/lib64/R/library
  packages:
    cluster, MASS, Matrix, mgcv, nlme, parallelly, survival, tibble
Warning message:
In install.packages(...) :
  installation of package ‘ggtree’ had non-zero exit status

**Comment by xiangpin** [comment]
please refer to the #518.

**Comment by Kirito-Ma** [comment]
Hi Xiangpin,

Thanks a lot. I have solved this problem!
