### ISSUE TITLE
branch.length

### ISSUE THREAD

**Issue by SolayMane** [YuLab-SMU/ggtree#524]
I have an issue with ggtree when displying my tree with branch.length="none", the tip labels don't appear correctly:

![image](https://user-images.githubusercontent.com/22656460/184497032-f336b94d-7000-42fb-8b3a-c008e044e9c0.png)

**Comment by brj1** [comment]
See #34.

**Comment by SolayMane** [comment]
<code>+ hexpand()</code> was the best solution

**Comment by nick-youngblut** [comment]
`+ coord_cartesian(clip="off")` doesn't seem to work

```
require(ape)
tr <- rtree(10)
tr$tip.label = gsub('^', 'A long label: ', tr$tip.label)
ggtree(tr) + geom_tiplab() + coord_cartesian(clip="off") 
```

![coord_cart](https://user-images.githubusercontent.com/2468572/203666364-15e20b07-ee14-4b45-a41b-34dcb6fd684d.png)

**Comment by nick-youngblut** [comment]
Neither does `+ ggplot2::xlim(0, 0.08)`

**Comment by nick-youngblut** [comment]
Works:

```
require(ape)
tr <- rtree(10)
tr$tip.label = gsub('^', 'A long label: ', tr$tip.label)
ggtree(tr) + geom_tiplab() + xlim_tree(4)
```

![xlim_tree](https://user-images.githubusercontent.com/2468572/203666715-65978dcf-38a4-47f3-9bcb-2a36a1f22ba3.png)
